import type { ProtocolToolManifest } from "../../../types.js";
import { POLYMARKET_GAMMA_DISCOVERY } from "../../../embeddings/polymarket/gamma.js";

// ── Events (4) ────────────────────────────────────────────────

export const GAMMA_EVENT_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "polymarket.gamma.events",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Browse prediction market events — filter by tag, status, liquidity/volume bounds, date range. Includes nested markets with prices.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field (e.g. volume24hr, liquidity, startDate)." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "slug", type: "string", description: "Filter by event slug(s), comma-separated." },
      { key: "tagSlug", type: "string", description: "Filter by tag slug." },
      { key: "tagId", type: "number", description: "Filter by tag ID." },
      { key: "excludeTagId", type: "string", description: "Exclude tag IDs, comma-separated." },
      { key: "relatedTags", type: "boolean", description: "Include related tags in response." },
      { key: "active", type: "boolean", description: "Filter active only." },
      { key: "closed", type: "boolean", description: "Filter closed only." },
      { key: "featured", type: "boolean", description: "Filter featured only." },
      { key: "archived", type: "boolean", description: "Filter archived events." },
      { key: "cyom", type: "boolean", description: "Filter create-your-own-market events." },
      { key: "liquidityMin", type: "number", description: "Minimum liquidity in USD." },
      { key: "liquidityMax", type: "number", description: "Maximum liquidity in USD." },
      { key: "volumeMin", type: "number", description: "Minimum volume in USD." },
      { key: "volumeMax", type: "number", description: "Maximum volume in USD." },
      { key: "startDateMin", type: "string", description: "Start date lower bound (ISO 8601)." },
      { key: "startDateMax", type: "string", description: "Start date upper bound (ISO 8601)." },
      { key: "endDateMin", type: "string", description: "End date lower bound (ISO 8601)." },
      { key: "endDateMax", type: "string", description: "End date upper bound (ISO 8601)." },
      { key: "recurrence", type: "string", description: "Filter by recurrence pattern." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { active: true, closed: false, liquidityMin: 1000, order: "volume24hr", ascending: false, limit: 10 },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.events"],
  },
  {
    toolId: "polymarket.gamma.event",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single event by ID — title, description, volume, liquidity, markets, tags.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "id", type: "string", required: true, description: "Event ID." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { id: "12345" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.event"],
  },
  {
    toolId: "polymarket.gamma.eventBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single event by URL slug.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "slug", type: "string", required: true, description: "Event slug." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { slug: "will-bitcoin-hit-100k" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.eventBySlug"],
  },
  {
    toolId: "polymarket.gamma.eventTags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get tags associated with an event.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "id", type: "string", required: true, description: "Event ID." },
    ],
    exampleParams: { id: "12345" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.eventTags"],
  },
];
