import type { ProtocolToolManifest } from "../../../types.js";
import { POLYMARKET_GAMMA_DISCOVERY } from "../../../embeddings/polymarket/gamma.js";

// ── Markets (4) ───────────────────────────────────────────────

export const GAMMA_MARKET_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "polymarket.gamma.markets",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Browse prediction markets — filter by status, liquidity/volume bounds, date range, sports, tags. Includes prices, clobTokenIds.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field (e.g. volume24hr, liquidityNum, endDate)." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "slug", type: "string", description: "Filter by slug(s), comma-separated." },
      { key: "clobTokenIds", type: "string", description: "Filter by CLOB token IDs, comma-separated." },
      { key: "conditionIds", type: "string", description: "Filter by condition IDs, comma-separated." },
      { key: "questionIds", type: "string", description: "Filter by question IDs, comma-separated." },
      { key: "closed", type: "boolean", description: "Filter by closed status." },
      { key: "tagId", type: "number", description: "Filter by tag ID." },
      { key: "relatedTags", type: "boolean", description: "Include related tags." },
      { key: "cyom", type: "boolean", description: "Create-your-own-market filter." },
      { key: "includeTag", type: "boolean", description: "Include tag data in response." },
      { key: "umaResolutionStatus", type: "string", description: "UMA resolution status filter." },
      { key: "liquidityMin", type: "number", description: "Min liquidity (USD)." },
      { key: "liquidityMax", type: "number", description: "Max liquidity (USD)." },
      { key: "volumeMin", type: "number", description: "Min volume (USD)." },
      { key: "volumeMax", type: "number", description: "Max volume (USD)." },
      { key: "startDateMin", type: "string", description: "Start date lower bound (ISO 8601)." },
      { key: "startDateMax", type: "string", description: "Start date upper bound (ISO 8601)." },
      { key: "endDateMin", type: "string", description: "End date lower bound (ISO 8601)." },
      { key: "endDateMax", type: "string", description: "End date upper bound (ISO 8601)." },
      { key: "gameId", type: "string", description: "Sports game ID filter." },
      { key: "sportsMarketTypes", type: "string", description: "Sports market types, comma-separated." },
      { key: "rewardsMinSize", type: "number", description: "Min rewards size." },
    ],
    exampleParams: { closed: false, liquidityMin: 1000, order: "volume24hr", ascending: false, limit: 10 },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.markets"],
  },
  {
    toolId: "polymarket.gamma.market",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single market by condition ID — question, outcomes, prices, clobTokenIds, negRisk.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "id", type: "string", required: true, description: "Market condition ID or numeric ID." },
      { key: "includeTag", type: "boolean", description: "Include tag data." },
    ],
    exampleParams: { id: "0xabc..." },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.market"],
  },
  {
    toolId: "polymarket.gamma.marketBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single market by URL slug.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "slug", type: "string", required: true, description: "Market slug." },
      { key: "includeTag", type: "boolean", description: "Include tag data." },
    ],
    exampleParams: { slug: "will-eth-hit-5000" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.marketBySlug"],
  },
  {
    toolId: "polymarket.gamma.marketTags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get tags associated with a market.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "id", type: "string", required: true, description: "Market condition ID." },
    ],
    exampleParams: { id: "0xabc..." },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.marketTags"],
  },
];
