import type { ProtocolToolManifest } from "../../../types.js";
import { POLYMARKET_GAMMA_DISCOVERY } from "../../../embeddings/polymarket/gamma.js";

// ── Tags (7) ──────────────────────────────────────────────────

export const GAMMA_TAG_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "polymarket.gamma.tags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "List all tags (categories) on Polymarket with pagination and sorting.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "isCarousel", type: "boolean", description: "Filter carousel tags only." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: {},
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tags"],
  },
  {
    toolId: "polymarket.gamma.tag",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single tag by ID.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "id", type: "string", required: true, description: "Tag ID." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { id: "42" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tag"],
  },
  {
    toolId: "polymarket.gamma.tagBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single tag by slug.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "slug", type: "string", required: true, description: "Tag slug." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { slug: "crypto" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tagBySlug"],
  },
  {
    toolId: "polymarket.gamma.relatedTags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get related tag IDs for a tag by ID.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "id", type: "string", required: true, description: "Tag ID." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { id: "42" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.relatedTags"],
  },
  {
    toolId: "polymarket.gamma.relatedTagsBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get related tag IDs for a tag by slug.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "slug", type: "string", required: true, description: "Tag slug." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { slug: "crypto" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.relatedTagsBySlug"],
  },
  {
    toolId: "polymarket.gamma.tagsRelatedToTag",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get full tag objects related to a tag by ID.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "id", type: "string", required: true, description: "Tag ID." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { id: "42" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tagsRelatedToTag"],
  },
  {
    toolId: "polymarket.gamma.tagsRelatedToTagBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get full tag objects related to a tag by slug.",
    mutating: false,
    actionKind: "read",
    params: [
      { key: "slug", type: "string", required: true, description: "Tag slug." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { slug: "crypto" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tagsRelatedToTagBySlug"],
  },
];
