import type { ProtocolToolManifest } from "../../types.js";
import { KYBERSWAP_ZAP_DISCOVERY } from "../../embeddings/kyberswap/zap.js";

export const ZAP_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "kyberswap.zap.in",
    namespace: "kyberswap",
    lifecycle: "active",
    description: "Add liquidity to a concentrated LP position via one-click zap. Handles routing, swaps, and position creation. Resolve tokenIn via khalani.tokens.search. Find pool address via dexscreener.tokenPairs. Use DEX_* IDs for dex param (query kyberswap.zap.list for options).",
    mutating: true,
    params: [
      { key: "chain", type: "string", required: true, description: "Chain slug or alias." },
      { key: "dex", type: "string", required: true, description: "DEX identifier — use official KyberSwap ZaaS DEX_* IDs (e.g. DEX_UNISWAPV3, DEX_QUICKSWAPV3ALGEBRA, DEX_PANCAKESWAPV3). Query kyberswap.zap.list for supported DEXes per chain." },
      { key: "pool", type: "string", required: true, description: "Pool contract address." },
      { key: "tokenIn", type: "string", required: true, description: "Input token address." },
      { key: "amountIn", type: "string", required: true, description: "Input amount in atomic units." },
      { key: "tickLower", type: "number", description: "Lower tick for new position." },
      { key: "tickUpper", type: "number", description: "Upper tick for new position." },
      { key: "positionRef", type: "string", description: "Position reference as expected by ZaaS API — NFT token ID for concentrated liquidity DEXes, wallet owner address for V2-like DEXes, ERC-1155 bin token ID for PancakeBin. Omit for new position." },
      { key: "slippageBps", type: "number", description: "Slippage tolerance in basis points." },
      { key: "approveExact", type: "boolean", description: "Approve exact amount instead of max." },
      { key: "dryRun", type: "boolean", description: "Preview route without executing." },
    ],
    exampleParams: { chain: "ethereum", dex: "DEX_UNISWAPV3", pool: "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640", tokenIn: "0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", amountIn: "1000000000", slippageBps: 100 },
    discovery: KYBERSWAP_ZAP_DISCOVERY["kyberswap.zap.in"],
  },
  {
    toolId: "kyberswap.zap.out",
    namespace: "kyberswap",
    lifecycle: "active",
    description: "Remove liquidity from a concentrated LP position — converts to a single output token. Resolve tokenOut via khalani.tokens.search.",
    mutating: true,
    params: [
      { key: "chain", type: "string", required: true, description: "Chain slug or alias." },
      { key: "dex", type: "string", required: true, description: "DEX identifier — use official KyberSwap ZaaS DEX_* IDs. Query kyberswap.zap.list for options." },
      { key: "pool", type: "string", required: true, description: "Pool contract address." },
      { key: "positionRef", type: "string", required: true, description: "Position reference — NFT token ID for CL DEXes, wallet address for V2-like, ERC-1155 token ID for PancakeBin." },
      { key: "tokenOut", type: "string", required: true, description: "Output token address." },
      { key: "liquidity", type: "string", description: "Liquidity amount to remove (omit for full)." },
      { key: "collectFee", type: "boolean", description: "Collect accumulated LP fees during exit (default: true)." },
      { key: "slippageBps", type: "number", description: "Slippage tolerance in basis points." },
      { key: "dryRun", type: "boolean", description: "Preview route without executing." },
    ],
    exampleParams: { chain: "ethereum", dex: "DEX_UNISWAPV3", pool: "0x88e6...", positionRef: "12345", tokenOut: "0xA0b8..." },
    discovery: KYBERSWAP_ZAP_DISCOVERY["kyberswap.zap.out"],
  },
  {
    toolId: "kyberswap.zap.migrate",
    namespace: "kyberswap",
    lifecycle: "active",
    description: "Migrate LP position between pools or DEXes in a single transaction.",
    mutating: true,
    params: [
      { key: "chain", type: "string", required: true, description: "Chain slug or alias." },
      { key: "dexFrom", type: "string", required: true, description: "Source DEX — use official DEX_* IDs." },
      { key: "dexTo", type: "string", required: true, description: "Destination DEX — use official DEX_* IDs." },
      { key: "poolFrom", type: "string", required: true, description: "Source pool address." },
      { key: "poolTo", type: "string", required: true, description: "Destination pool address." },
      { key: "sourcePositionRef", type: "string", required: true, description: "Source position reference — NFT token ID for CL DEXes, wallet address for V2-like, ERC-1155 token ID for PancakeBin." },
      { key: "tickLower", type: "number", description: "Lower tick for destination position." },
      { key: "tickUpper", type: "number", description: "Upper tick for destination position." },
      { key: "liquidity", type: "string", description: "Liquidity to migrate (omit for full)." },
      { key: "collectFee", type: "boolean", description: "Collect accumulated LP fees during migration (default: true)." },
      { key: "slippageBps", type: "number", description: "Slippage tolerance in basis points." },
      { key: "dryRun", type: "boolean", description: "Preview route without executing." },
    ],
    exampleParams: { chain: "ethereum", dexFrom: "DEX_UNISWAPV3", dexTo: "DEX_PANCAKESWAPV3", poolFrom: "0xaaa...", poolTo: "0xbbb...", sourcePositionRef: "12345" },
    discovery: KYBERSWAP_ZAP_DISCOVERY["kyberswap.zap.migrate"],
  },
  {
    toolId: "kyberswap.zap.list",
    namespace: "kyberswap",
    lifecycle: "active",
    description: "List supported ZaaS DEX protocols on a chain for zap-in/out/migrate. Returns official DEX_* IDs that can be passed directly to zap tools.",
    mutating: false,
    params: [
      { key: "chain", type: "string", required: true, description: "Chain slug or alias (e.g. polygon, ethereum, base, arbitrum)." },
    ],
    exampleParams: { chain: "polygon" },
    discovery: KYBERSWAP_ZAP_DISCOVERY["kyberswap.zap.list"],
  },
];
