import type { ProtocolToolManifest } from "../../types.js";

export const ZAP_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "kyberswap.zap.in",
    namespace: "kyberswap",
    lifecycle: "active",
    description: "Add liquidity to a concentrated LP position via one-click zap. Handles routing, swaps, and position creation.",
    mutating: true,
    params: [
      { key: "chain", type: "string", required: true, description: "Chain slug or alias." },
      { key: "dex", type: "string", required: true, description: "DEX protocol (e.g. uniswapv3, pancakev3)." },
      { key: "pool", type: "string", required: true, description: "Pool contract address." },
      { key: "tokenIn", type: "string", required: true, description: "Input token address." },
      { key: "amountIn", type: "string", required: true, description: "Input amount in atomic units." },
      { key: "tickLower", type: "number", description: "Lower tick for new position." },
      { key: "tickUpper", type: "number", description: "Upper tick for new position." },
      { key: "positionId", type: "string", description: "Existing position ID to add to." },
      { key: "slippageBps", type: "number", description: "Slippage tolerance in basis points." },
      { key: "approveExact", type: "boolean", description: "Approve exact amount instead of max." },
      { key: "dryRun", type: "boolean", description: "Preview route without executing." },
    ],
    exampleParams: { chain: "ethereum", dex: "uniswapv3", pool: "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640", tokenIn: "0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", amountIn: "1000000000", slippageBps: 100 },
  },
  {
    toolId: "kyberswap.zap.out",
    namespace: "kyberswap",
    lifecycle: "active",
    description: "Remove liquidity from a concentrated LP position — converts to a single output token.",
    mutating: true,
    params: [
      { key: "chain", type: "string", required: true, description: "Chain slug or alias." },
      { key: "dex", type: "string", required: true, description: "DEX protocol." },
      { key: "pool", type: "string", required: true, description: "Pool contract address." },
      { key: "positionId", type: "string", required: true, description: "LP position NFT ID." },
      { key: "tokenOut", type: "string", required: true, description: "Output token address." },
      { key: "liquidity", type: "string", description: "Liquidity amount to remove (omit for full)." },
      { key: "slippageBps", type: "number", description: "Slippage tolerance in basis points." },
      { key: "dryRun", type: "boolean", description: "Preview route without executing." },
    ],
    exampleParams: { chain: "ethereum", dex: "uniswapv3", pool: "0x88e6...", positionId: "12345", tokenOut: "0xA0b8..." },
  },
  {
    toolId: "kyberswap.zap.migrate",
    namespace: "kyberswap",
    lifecycle: "active",
    description: "Migrate LP position between pools or DEXes in a single transaction.",
    mutating: true,
    params: [
      { key: "chain", type: "string", required: true, description: "Chain slug or alias." },
      { key: "dexFrom", type: "string", required: true, description: "Source DEX protocol." },
      { key: "dexTo", type: "string", required: true, description: "Destination DEX protocol." },
      { key: "poolFrom", type: "string", required: true, description: "Source pool address." },
      { key: "poolTo", type: "string", required: true, description: "Destination pool address." },
      { key: "positionId", type: "string", required: true, description: "Source LP position NFT ID." },
      { key: "tickLower", type: "number", description: "Lower tick for destination position." },
      { key: "tickUpper", type: "number", description: "Upper tick for destination position." },
      { key: "liquidity", type: "string", description: "Liquidity to migrate (omit for full)." },
      { key: "slippageBps", type: "number", description: "Slippage tolerance in basis points." },
      { key: "dryRun", type: "boolean", description: "Preview route without executing." },
    ],
    exampleParams: { chain: "ethereum", dexFrom: "uniswapv3", dexTo: "pancakev3", poolFrom: "0xaaa...", poolTo: "0xbbb...", positionId: "12345" },
  },
];
