import type { JsonSchemaProperty, ToolDef } from "../types.js";

const stringList = (description: string): JsonSchemaProperty => ({
  type: "array",
  description,
  items: { type: "string" },
});

export const TWITTER_ACCOUNT_TOOLS: readonly ToolDef[] = [
  {
    name: "twitter_account",
    kind: "internal",
    mutating: false,
    pressureSafety: "read_only",
    actionKind: "read",
    requiresEnv: "RETTIWT_API_KEY",
    description: [
      "Use the configured secondary Twitter/X account via Rettiwt for read-only research.",
      "Supports account_status, user_details, user_search, user_timeline, user_replies, user_followers, user_following, tweet_details, tweet_search, tweet_replies, tweet_likers, tweet_retweeters, and space_details.",
      "This v1 tool never posts, likes, retweets, follows, bookmarks, reads DMs, uploads media, or changes profile/account state.",
      "response_format: 'concise' (default) strips image/banner/bio/entities noise and keeps the signal fields; 'detailed' returns the verbatim client payload.",
      "RETTIWT_API_KEY is a base64 cookie-session secret; never ask to reveal it or include it in output.",
    ].join(" "),
    parameters: {
      type: "object",
      additionalProperties: false,
      required: ["action"],
      properties: {
        action: {
          type: "string",
          enum: [
            "account_status",
            "tweet_details",
            "tweet_search",
            "tweet_replies",
            "tweet_likers",
            "tweet_retweeters",
            "space_details",
            "user_details",
            "user_search",
            "user_timeline",
            "user_replies",
            "user_followers",
            "user_following",
          ],
          description: "Read-only Twitter/X operation to perform.",
        },
        response_format: {
          type: "string",
          enum: ["concise", "detailed"],
          description:
            "concise (default) strips image/banner/bio/entities noise; detailed returns the verbatim client payload.",
        },
        username: { type: "string", description: "Twitter/X username, with or without @." },
        userId: { type: "string", description: "Numeric Twitter/X user id." },
        query: {
          type: "string",
          description:
            "Required for user_search. For tweet_search, shortcut text mapped to filter.includeWords.",
        },
        tweetId: { type: "string", description: "Numeric tweet id." },
        spaceId: { type: "string", description: "Twitter/X Space id." },
        count: { type: "number", description: "Batch size. Max 20 for timelines/search, max 100 for social lists." },
        cursor: { type: "string", description: "Cursor returned by a previous call." },
        sortBy: {
          type: "string",
          enum: ["LATEST", "LIKES", "RELEVANCE"],
          description: "Sort order for tweet_replies.",
        },
        withReplays: { type: "boolean", description: "space_details only: include replay information." },
        withListeners: { type: "boolean", description: "space_details only: include listener information." },
        filter: {
          type: "object",
          description: "tweet_search filter. Provide query or at least one filter field.",
          additionalProperties: false,
          properties: {
            fromUsers: stringList("Usernames whose tweets to search."),
            toUsers: stringList("Usernames addressed by matching tweets."),
            mentions: stringList("Mentioned usernames."),
            hashtags: stringList("Hashtags without #."),
            includeWords: stringList("Words that must appear."),
            optionalWords: stringList("Words where any may appear."),
            excludeWords: stringList("Words to exclude."),
            includePhrase: { type: "string", description: "Exact phrase to search." },
            language: { type: "string", description: "Language code such as en or pl." },
            list: { type: "string", description: "Twitter/X list id to search within." },
            maxId: { type: "string", description: "Tweet id before which to search." },
            sinceId: { type: "string", description: "Tweet id after which to search." },
            quoted: { type: "string", description: "Quoted tweet id." },
            startDate: { type: "string", description: "Inclusive ISO datetime start." },
            endDate: { type: "string", description: "Inclusive ISO datetime end." },
            minLikes: { type: "number", description: "Minimum likes." },
            minReplies: { type: "number", description: "Minimum replies." },
            minRetweets: { type: "number", description: "Minimum retweets." },
            onlyLinks: { type: "boolean", description: "Only posts with links/media." },
            onlyOriginal: { type: "boolean", description: "Only original posts." },
            onlyReplies: { type: "boolean", description: "Only replies." },
            onlyText: { type: "boolean", description: "Only text-only posts." },
            top: { type: "boolean", description: "Return top tweets instead of latest where supported." },
          },
        },
      },
    },
  },
];
