/**
 * Session-memories CRUD — compatibility façade.
 *
 * The implementation has been split into focused sibling modules (render,
 * create, read, stats, resolution, embeddings); this file re-exports the
 * IDENTICAL public surface so existing importers see no difference.
 *
 * Insert path:
 *   - `body_md` is generated by the repo (not the caller) via `renderBodyMd`
 *     so the materialized column never drifts from the structured fields.
 *   - `content_hash = sha256(theme + happened_md + did_md + tried_md)` is
 *     generated before SQL — narrative core only, NOT body_md / outstanding
 *     (see types.ts for rationale).
 *   - Dedup is per (session_id, content_hash) on active rows — same content
 *     in the same session is a no-op insert. Returns `{ inserted, memory }`.
 *
 * Resolution path (`markOutstandingResolved`):
 *   - Updates one element of the `outstanding_items` JSONB array by id.
 *   - Re-renders `body_md` from the new state. Caller is responsible for
 *     re-embedding and updating `embedding` + `embedding_model` + dim if the
 *     hash changes substantially; this repo does NOT re-embed on its own
 *     (embedding service IO must be explicit at call sites).
 */

export { prepareMemoryRender, type PreparedMemoryRender } from "./render.js";

export { insertPreparedMemory, insertMemories, type InsertResult } from "./create.js";

export {
  getById,
  listActiveBySession,
  listUnresolvedOutstandingItems,
  type UnresolvedOutstandingItem,
} from "./read.js";

export { getSessionMemoryStats, type SessionMemoryStats } from "./stats.js";

export { markOutstandingResolved, type ResolveOutstandingResult } from "./resolution.js";

export { updateEmbedding } from "./embeddings.js";
