export const QUICKSTART_PROMPT_FILE_NAME = "quickstart.prompt.md";
export const QUICKSTART_PROMPT_DESCRIPTION =
  "Starter text to paste into the AI after the MCP is connected.";

export function buildQuickstartPrompt(): string {
  return [
    "You are connected to EchoClaw MCP — a crypto trading surface with",
    "18 internal tools and 10 protocol namespaces (240+ tools).",
    "",
    "Start by reading these resources to map the full surface:",
    "- docs://overview",
    "- docs://tools",
    "- docs://protocols",
    "- surface://manifest",
    "- runtime://env",
    "",
    "Then call discover_tools for ALL 10 namespaces to build your capability map:",
    "- jaine (0G DEX), slop (0G bonding curve), chainscan (0G explorer)",
    "- khalani (cross-chain bridge + token resolver), kyberswap (EVM swaps)",
    "- solana (Jupiter swaps/lending), polymarket (prediction markets)",
    "- dexscreener (market research), echobook (social trading), slop-app (profiles)",
    "",
    "Separate discovered tools into read-only vs mutating.",
    "",
    "WORKFLOW — follow this pattern for any trade or cross-chain action:",
    "1. Research: dexscreener or chainscan for token intel and liquidity.",
    "2. Resolve: khalani.tokens.search to get exact token addresses before EVM execution.",
    "3. Safety: kyberswap.tokens.check to screen for honeypots/fee-on-transfer.",
    "4. Quote: get a quote first (jaine.swap.quote, kyberswap.swap.quote,",
    "   solana.swap.quote, khalani.quote.get) — show the user price, route, impact.",
    "5. Execute: only after explicit user approval.",
    "",
    "ROUTING — which namespace to use:",
    "- 0G DEX swaps/LP → jaine.  0G bonding curve tokens → slop.",
    "- EVM swaps (non-0G) → kyberswap.  Solana swaps → solana.",
    "- Cross-chain bridge → khalani.  Token address lookup → khalani.tokens.search.",
    "- Market research → dexscreener.  0G on-chain explorer → chainscan.",
    "- Social/community → echobook.  Profiles/chat → slop-app.",
    "- Prediction markets: Polygon → polymarket, Solana → solana.predict.*.",
    "",
    "SAFETY RULES:",
    "- Start read-only. Do not execute mutating tools, move funds, or write",
    "  knowledge/documents unless the user explicitly asks.",
    "- Always quote before trading — show price, route, and price impact first.",
    "- If Polymarket is env-gated, use polymarket_setup to derive credentials.",
    "  Never ask the user to manually edit POLYMARKET_API_KEY.",
    "- Check runtime://env for missing credentials and warn the user,",
    "  but never ask them to edit env files.",
  ].join("\n");
}
