import { embeddingText } from "../../_embedding-text.js";
import type { ToolDiscoveryMetadata } from "../../types.js";

const read = (text: string): ToolDiscoveryMetadata => ({ embeddingText: embeddingText(text), sideEffectLevel: "none" });
const trade = (text: string): ToolDiscoveryMetadata => ({ embeddingText: embeddingText(text), sideEffectLevel: "high" });

export const HYPERLIQUID_DISCOVERY = {
  "hyperliquid.perp.markets": read("Inspect Hyperliquid HyperCore perpetual markets, including tradable coins, size precision, price precision, asset leverage limits, and current market context. Use when: researching whether a perp can be traded before proposing an order or risk setup. This is a read-only venue view and does not create exposure. Example queries: list Hyperliquid perpetual markets, what is BTC max leverage on Hyperliquid, pokaz rynki perp for ETH, can I trade SOL perps here."),
  "hyperliquid.perp.positions": read("Inspect selected-wallet Hyperliquid HyperCore perpetual positions with size, entry price, mark price, unrealized PnL, liquidation information, and authoritative stop-loss coverage. Use when: checking current leveraged exposure, deciding whether a position is protected, or reviewing risk before another perp action. Coverage can be protected, consolidating, or unprotected, so do not assume a resting stop exists. Example queries: show my Hyperliquid positions, pokaz moje pozycje, is my ETH perp protected, where is my BTC liquidation price."),
  "hyperliquid.perp.orders": read("List selected-wallet Hyperliquid HyperCore frontend open orders, including resting entries, reduce-only exits, and stop-loss orders used for position protection. Use when: inspecting what remains active before canceling, modifying, scaling, or reconciling a perpetual position. Compare these orders with the position coverage state; an order list alone does not prove the position is safely protected. Example queries: show Hyperliquid open orders, find my BTC stop, pokaz moje zlecenia, which ETH entries are still resting."),
  "hyperliquid.perp.fills": read("List selected-wallet Hyperliquid HyperCore perpetual fills with execution price, size, side, and timing so completed leveraged trades can be reviewed independently of still-open orders. Use when: checking whether an entry, exit, or partial close actually executed, especially after a network interruption or partial acceptance. Fills are historical evidence and do not by themselves confirm current protection. Example queries: show Hyperliquid fills, BTC perp executions today, pokaz moje wypelnienia, did my ETH close fill."),
  "hyperliquid.perp.funding": read("List selected-wallet Hyperliquid HyperCore perpetual funding payments and related history for open or recently closed perp exposure. Use when: measuring the carrying cost of a leveraged position, reviewing why PnL changed, or deciding whether to keep a directional trade open. Funding can be a cost or a credit and changes over time, so it should not be treated as a guaranteed yield. Example queries: Hyperliquid funding paid, funding history for BTC, pokaz funding ETH, how much funding did my short pay."),
  "hyperliquid.account.overview": read("Inspect selected-wallet Hyperliquid HyperCore clearinghouse collateral, available margin, account value, and margin state without submitting an order. Use when: checking capacity before a perp trade, interpreting liquidation risk, or understanding why a policy gate rejects a leverage or margin change. The view is informational and market prices can move after it is read. Example queries: Hyperliquid account overview, available perp margin, pokaz moje collateral, how much buying power do I have for BTC."),
  "hyperliquid.spot.markets": read("Inspect Hyperliquid HyperCore spot markets and their current contexts, including available pairs and market information needed before considering a spot order. Use when: researching whether a listed asset has a direct Hyperliquid spot market, comparing pairs, or checking the venue before a purchase or sale. The market view only reads data and cannot move assets. Example queries: Hyperliquid spot markets, HYPE USDC market, pokaz rynki spot, is PURR available on Hyperliquid spot."),
  "hyperliquid.spot.balances": read("Inspect selected-wallet Hyperliquid HyperCore spot balances to see assets held in the venue spot account before planning a purchase, sale, or later transfer request. Use when: checking holdings, confirming an available asset balance, or reconciling a completed spot trade. Balances are read-only and do not imply approval for an egress action. Example queries: my Hyperliquid spot balances, HYPE balance, pokaz moje saldo spot, do I have USDC available on Hyperliquid."),
  "hyperliquid.market.book": read("Inspect a Hyperliquid HyperCore L2 order book for a selected spot or perpetual market, including bid and ask depth used to estimate liquidity and likely slippage. Use when: evaluating whether an order size is realistic before proposing or submitting a trade. Order book depth is a snapshot, not a guaranteed execution price, and can change quickly. Example queries: BTC Hyperliquid order book, ETH perp depth, pokaz order book SOL, how much liquidity is near the HYPE spot price."),
  "hyperliquid.market.watchCandles": read("Watch a Hyperliquid market's candles locally. Enable it to backfill the interval's normal history window into the encrypted local database, then keep that pair current through a bounded WebSocket subscription; disable it to stop writes while retaining history. Use when: repeated analysis would otherwise poll the venue. Example queries: watch BTC one hour candles, start HYPE 15m candle watch, stop watching ETH candles."),
  "hyperliquid.market.candles": read("Read Hyperliquid OHLCV candles newest first with precise coverage and live-watch metadata. Use when an analysis needs raw recent history: watched pairs are served immediately from the local candle store, while an unwatched pair makes exactly one venue snapshot request and is not saved. Limit output to the window actually needed. Example queries: get 200 BTC 1h candles, show HYPE daily candles, read ETH 15m candle coverage."),
  "hyperliquid.market.scan": read("Scan Hyperliquid candles into compact technical verdicts without returning raw rows. Use when: assessing percent change, high/low breakouts, volume spikes, SMA or EMA crosses, RSI zones, or range width; calculations use finite decimal arithmetic and report skipped malformed stored rows. Watched pairs use local history, while an unwatched pair uses one snapshot only. Example queries: scan BTC RSI 14, find HYPE volume spike, check ETH moving-average cross."),
  "hyperliquid.risk.proposeSetup": trade("Create a Hyperliquid HyperCore session risk proposal with leverage and notional caps for one selected perpetual market. Use when: the user wants to negotiate risk before trading, or asks Vex to prepare safer limits for review. The proposal changes no market exposure and cannot activate itself; the user confirms or adjusts it in the main-owned card, where asset maximum leverage is checked. Example queries: propose 3x BTC risk setup, set conservative ETH perp limits, przygotuj limity ryzyka SOL."),
  "hyperliquid.perp.open": trade("Open a Hyperliquid HyperCore perpetual long or short using policy-bounded leverage, notional, and slippage checks before signing. When a stop is required or supplied, the entry and reduce-only stop are submitted atomically as a normalTpsl group; the user-owned opt-out policy is the only route to a plain entry. Use when: entering a planned, risk-reviewed perp position. Stop losses are not guaranteed fills. Example queries: long BTC with a stop loss, short ETH on Hyperliquid, open a 3x SOL long with stop at 120."),
  "hyperliquid.perp.close": trade("Close or reduce a Hyperliquid HyperCore perpetual position with an explicit reduce-only immediate-or-cancel order and a bounded slippage price. Use when: exiting a long or short, taking partial profit, or reducing risk without accidentally reversing the position. The order is constrained to existing exposure and execution can still be partial when liquidity is limited. Example queries: close my BTC perp, reduce ETH long by half, zamknij moja pozycje SOL, exit my Hyperliquid short now."),
  "hyperliquid.perp.setTpsl": trade("Place or replace a Hyperliquid HyperCore full-position stop-loss or take-profit instruction while preserving protection during the replacement sequence. Use when: moving a standing stop, restoring full-position coverage after consolidation, or updating a planned exit for an existing perp. The gate checks position state, side, reduce-only behavior, and liquidation safety before the request proceeds. Example queries: move my BTC stop to 60000, set ETH stop loss below entry, restore the full-position stop for my SOL long."),
  "hyperliquid.perp.modifyOrder": trade("Update a Hyperliquid HyperCore perpetual resting order after validating its changed price, size, and protection implications against the current position state. Use when: adjusting an unfilled entry or exit rather than placing an unrelated new order. A modification that would orphan the sole protective stop or violate policy is rejected. Example queries: modify my ETH perp order, move my BTC entry lower, change the limit price on my SOL short, update my resting Hyperliquid order."),
  "hyperliquid.perp.cancelOrders": trade("Cancel named Hyperliquid HyperCore perpetual orders while preserving the only valid stop-loss coverage for any open position. Use when: removing a resting entry, replacing an outdated non-protective order, or cleaning up unfilled instructions. The protection gate refuses a cancellation that would orphan the sole full-position stop; cancel a protected entry only after reviewing coverage. Example queries: cancel my BTC entry, remove my old ETH limit order, anuluj moje zlecenie SOL, cancel this resting Hyperliquid order."),
  "hyperliquid.perp.setLeverage": trade("Set Hyperliquid HyperCore perpetual leverage within the user-confirmed policy cap and the selected asset maximum, then re-check estimated liquidation and stop-loss headroom. Use when: changing risk on an existing or planned perp position after the user has chosen the allowed limits. Higher leverage can make liquidation more likely and the model cannot raise the cap on its own. Example queries: set BTC leverage to 3x, lower my ETH leverage, ustaw leverage SOL na 2x, what leverage can I use for this perp."),
  "hyperliquid.perp.adjustMargin": trade("Update isolated margin on a Hyperliquid HyperCore perpetual position only after recalculating liquidation distance, maintenance headroom, and standing stop-loss safety. Use when: adding collateral to reduce risk or requesting a permitted margin reduction from a protected position. A request that would make existing protection unsafe is rejected rather than silently weakening the position. Example queries: add margin to ETH perp, remove some BTC isolated margin, dodaj margin do SOL, how much margin can I safely withdraw from this position."),
  "hyperliquid.perp.twap": trade("Submit a Hyperliquid HyperCore perpetual TWAP only for a position that already has valid standing full-position stop-loss coverage. Use when: scaling a protected long or short gradually instead of sending a single large order into limited liquidity. The protection gate blocks TWAP if coverage is missing or only transient consolidation protection remains. Example queries: TWAP buy BTC perp, scale into my protected ETH long, kupuj SOL perps over 30 minutes, gradually reduce this Hyperliquid short."),
  "hyperliquid.spot.trade": trade("Place a Hyperliquid HyperCore spot buy or sell after validating the market, price precision, size precision, minimum notional, and estimated slippage against available order-book depth. Use when: acquiring or selling a listed spot asset without creating perpetual leverage. This trade changes venue balances, so review the asset, amount, and execution constraints before confirming. Example queries: buy HYPE spot on Hyperliquid, sell PURR for USDC, kup HYPE za USDC, place a limit order for spot BTC."),
  "hyperliquid.deposit": trade("Deposit native USDC from Arbitrum One to the pinned Bridge2 contract to fund the selected Hyperliquid account. Use when: the wallet already holds native Arbitrum USDC and the user wants collateral credited to the same sender account. The recipient is fixed, never model-supplied. Deposits below 5 USDC are permanently lost; credit normally arrives in less than one minute, then verify with the account overview. Example queries: deposit 25 USDC to Hyperliquid, fund my Hyperliquid account, wplac USDC do Hyperliquid."),
  "hyperliquid.transfer.usdClass": trade("Move USDC between the Hyperliquid HyperCore spot account and the perpetual collateral account without leaving the venue. Use when: funding a planned perp position from spot USDC, or returning surplus collateral to spot after reducing risk. Moving USDC out of perps is collateral-sensitive and is blocked unless protected open positions retain required maintenance headroom. Example queries: move 100 USDC to Hyperliquid perps, transfer collateral back to spot, przenies USDC z perps na spot."),
  "hyperliquid.withdraw": trade("Withdraw USDC from Hyperliquid HyperCore to a specified external EVM address. Use when: the user explicitly wants funds to leave the venue after reviewing destination and amount. This is fund egress, so it always requests an approval intent when the user safety toggle is enabled, even during a full-permission session. Open perp margin and stop-loss coverage are checked before signing. Example queries: withdraw 50 USDC from Hyperliquid, send USDC to this wallet, wyplac USDC z Hyperliquid."),
  "hyperliquid.transfer.send": trade("Send USD collateral or a named spot token from Hyperliquid HyperCore to an external EVM recipient. Use when: the user has explicitly named a destination and asset, not merely asked to rebalance funds internally. This is an egress operation with recipient data in the approval preview; policy can require approval even in autonomous-full sessions. Collateral-sensitive sends are refused when protected perp margin cannot be preserved. Example queries: send 20 USDC to 0x..., transfer HYPE to my wallet, wyslij token z Hyperliquid."),
  "hyperliquid.vault.overview": read("Inspect selected-wallet Hyperliquid HyperCore vault participation, including HLP or other vault equity balances reported by the venue. Use when: reviewing whether funds are already deposited in a vault, comparing owned vault shares, or preparing a later agent-mediated deposit or withdrawal request. This read does not transfer capital, claim yield, or guarantee a vault's performance. Example queries: show my Hyperliquid vaults, do I hold HLP, pokaz moje udzialy HLP, what vault equity do I have."),
  "hyperliquid.vault.transfer": trade("Deposit USDC into or withdraw USDC from a Hyperliquid HyperCore vault, including HLP, using the named vault address and exact amount. Use when: the user has chosen a vault and understands that vault returns and liquidity are not guaranteed. A deposit sourced from perp collateral is checked against protection and maintenance headroom before signing. The action changes venue balances and remains approval-gated by session policy. Example queries: deposit 100 USDC into HLP, withdraw from this Hyperliquid vault, wplac USDC do HLP."),
  "hyperliquid.staking.overview": read("Inspect selected-wallet Hyperliquid HYPE staking and delegation summary, including validator-related balances reported by HyperCore. Use when: checking whether HYPE is available in spot or staking balance, reviewing existing delegation, or deciding whether a later delegate, undelegate, deposit, or withdrawal instruction is appropriate. This read-only view does not move HYPE or make a validator recommendation. Example queries: show my HYPE staking, Hyperliquid delegations, pokaz staking HYPE, where is my delegated HYPE."),
  "hyperliquid.staking.delegate": trade("Submit a HYPE delegation or undelegation for a specified validator using an exact base-unit amount held in Hyperliquid staking. Use when: the user has selected the validator and explicitly wants to change stake allocation. This action is not a guaranteed yield product; validator and protocol risks remain. Review validator address, direction, and amount before approval because the operation changes staking state. Example queries: delegate HYPE to this validator, undelegate 1 HYPE, deleguj HYPE, wycofaj delegacje HYPE."),
  "hyperliquid.staking.transfer": trade("Move HYPE between the Hyperliquid spot account and the staking balance using a precise 1e8-base-unit amount. Use when: preparing HYPE for delegation or returning it from staking before a later spot use. This changes account state but does not choose a validator or claim rewards. Confirm the direction and base-unit amount carefully; the tool rejects non-canonical integers before signing. Example queries: deposit 2 HYPE into staking, withdraw HYPE from staking, przenies HYPE do stakingu."),
  "hyperliquid.rewards.claim": trade("Claim available Hyperliquid HyperCore rewards for the selected wallet without placing a trade or changing a perpetual position. Use when: the user asks to collect already-earned rewards after reviewing their account or staking status. Claiming does not guarantee an amount, and the response must be checked for venue acceptance. The mutation is approval-gated according to the session policy. Example queries: claim my Hyperliquid rewards, collect HYPE rewards, odbierz nagrody Hyperliquid."),
  "hyperliquid.builder.approveFee": trade("Approve the release-configured 0.025% Hyperliquid builder allowance for the selected wallet. Use when: diagnosing or explicitly refreshing the venue allowance after the user has accepted the first-entry Hyperliquid disclosure, which covers the fee on filled notional. Normal order flow checks maxBuilderFee and submits one best-effort approval automatically when needed; an unavailable or rejected allowance never blocks the order and simply omits the builder field. Example queries: approve Hyperliquid builder fee, refresh the 0.025 percent allowance, zatwierdz oplata buildera."),
  "hyperliquid.workspace.enter": read("Request the dedicated Hypervexing workspace for focused Hyperliquid HyperCore position monitoring, protection review, and trading conversation. Use when: the user is actively working with Hyperliquid and a specialized workspace would make the current session easier to follow. This changes only local presentation, never positions, orders, permissions, or policy. First entry still waits for the main-owned risk acknowledgment before the renderer transitions. Example queries: hypervexing, open the Hypervexing workspace, switch to the Hyperliquid trading view, pokaz tryb Hypervexing."),
  "hyperliquid.workspace.exit": read("Request a return from the dedicated Hypervexing workspace to the normal Vex workspace without changing any Hyperliquid HyperCore position, order, balance, permission, or policy. Use when: the user asks the agent to leave the focused Hyperliquid presentation or the specialized workspace is no longer useful for the current task. This is a local presentation request and does not close trades or cancel protection. Example queries: exit Hypervexing, return to normal Vex, leave the Hyperliquid workspace, wroc do zwyklego widoku."),
} satisfies Record<string, ToolDiscoveryMetadata>;
