import type { ProtocolParamDef, ProtocolToolManifest } from "../types.js";
import { HYPERLIQUID_DISCOVERY } from "../embeddings/hyperliquid/core.js";

type HyperliquidToolId = keyof typeof HYPERLIQUID_DISCOVERY;

const string = (key: string, description: string, required = false): ProtocolParamDef => ({ key, type: "string", description, ...(required ? { required: true } : {}) });
const number = (key: string, description: string, required = false): ProtocolParamDef => ({ key, type: "number", description, ...(required ? { required: true } : {}) });
const boolean = (key: string, description: string, required = false): ProtocolParamDef => ({ key, type: "boolean", description, ...(required ? { required: true } : {}) });
const object = (key: string, description: string, required = false): ProtocolParamDef => ({ key, type: "object", description, ...(required ? { required: true } : {}) });
const read = (toolId: HyperliquidToolId, description: string, params: ProtocolParamDef[] = [], exampleParams: Record<string, unknown> = {}): ProtocolToolManifest => ({ toolId, namespace: "hyperliquid", lifecycle: "active", description, mutating: false, actionKind: "read", params, exampleParams, discovery: HYPERLIQUID_DISCOVERY[toolId] });
const mutate = (toolId: HyperliquidToolId, description: string, params: ProtocolParamDef[], exampleParams: Record<string, unknown>): ProtocolToolManifest => ({ toolId, namespace: "hyperliquid", lifecycle: "active", description, mutating: true, actionKind: "external_post", params, exampleParams, discovery: HYPERLIQUID_DISCOVERY[toolId] });
const walletBroadcast = (toolId: HyperliquidToolId, description: string, params: ProtocolParamDef[], exampleParams: Record<string, unknown>): ProtocolToolManifest => ({ toolId, namespace: "hyperliquid", lifecycle: "active", description, mutating: true, actionKind: "user_wallet_broadcast", params, exampleParams, discovery: HYPERLIQUID_DISCOVERY[toolId] });
const localWrite = (toolId: HyperliquidToolId, description: string, params: ProtocolParamDef[], exampleParams: Record<string, unknown>): ProtocolToolManifest => ({ toolId, namespace: "hyperliquid", lifecycle: "active", description, mutating: true, actionKind: "local_write", params, exampleParams, discovery: HYPERLIQUID_DISCOVERY[toolId] });
const localMarketWrite = (toolId: HyperliquidToolId, description: string, params: ProtocolParamDef[], exampleParams: Record<string, unknown>): ProtocolToolManifest => ({ toolId, namespace: "hyperliquid", lifecycle: "active", description, mutating: false, actionKind: "local_write", params, exampleParams, discovery: HYPERLIQUID_DISCOVERY[toolId] });
const localPresentation = (toolId: HyperliquidToolId, description: string): ProtocolToolManifest => ({ toolId, namespace: "hyperliquid", lifecycle: "active", description, mutating: false, actionKind: "local_write", params: [], exampleParams: {}, discovery: HYPERLIQUID_DISCOVERY[toolId] });

export const HYPERLIQUID_TOOLS: readonly ProtocolToolManifest[] = [
  read("hyperliquid.perp.markets", "Search Core perpetual markets by ticker (query): precision, leverage limits, funding, and open interest. Returns a compact, bounded list.", [
    string("query", "Case-insensitive substring filter on the coin ticker, e.g. 'cash' matches CASHCAT."),
    number("limit", "Max markets returned (default 20, cap 50)."),
  ], { query: "BTC", limit: 20 }),
  read("hyperliquid.perp.positions", "Show selected-wallet perpetual positions plus live stop-loss coverage."),
  read("hyperliquid.perp.orders", "List selected-wallet frontend open orders."),
  read("hyperliquid.perp.fills", "List selected-wallet perpetual fills, newest-first and bounded.", [number("startTime", "Optional epoch milliseconds lower bound."), number("limit", "Max fills returned (default 50, cap 200).")]),
  read("hyperliquid.perp.funding", "List selected-wallet funding payments, newest-first and bounded.", [number("startTime", "Optional epoch milliseconds lower bound."), number("limit", "Max rows returned (default 50, cap 200).")]),
  read("hyperliquid.account.overview", "Show selected-wallet clearinghouse account state."),
  read("hyperliquid.spot.markets", "Search Hyperliquid spot markets by pair (query): price, mid, and daily volume. Returns a compact, bounded list.", [string("query", "Case-insensitive substring filter on the pair name, e.g. 'purr' matches PURR/USDC."), number("limit", "Max markets returned (default 20, cap 50).")], { query: "HYPE", limit: 20 }),
  read("hyperliquid.spot.balances", "Show selected-wallet spot-clearinghouse balances."),
  read("hyperliquid.market.book", "Show a Hyperliquid L2 order book.", [string("coin", "Market coin, e.g. BTC.", true)], { coin: "BTC" }),
  localMarketWrite("hyperliquid.market.watchCandles", "Enable or disable a local persisted candle watch; enabling backfills and then keeps the pair fresh by WebSocket.", [string("coin", "Market coin, e.g. BTC.", true), string("interval", "1m, 5m, 15m, 1h, 4h, or 1d.", true), boolean("enabled", "True starts the watch; false stops writes but retains stored rows.", true)], { coin: "BTC", interval: "1h", enabled: true }),
  read("hyperliquid.market.candles", "Read locally stored candles newest-first, or make one snapshot request when the pair is not watched.", [string("coin", "Market coin, e.g. BTC.", true), string("interval", "1m, 5m, 15m, 1h, 4h, or 1d.", true), number("limit", "Stored or snapshot candle count, 1 through 500.", true)], { coin: "BTC", interval: "1h", limit: 200 }),
  read("hyperliquid.market.scan", "Scan stored candles with compact technical-signal verdicts; unwatched pairs use one snapshot without persistence.", [string("coin", "Market coin, e.g. BTC.", true), string("interval", "1m, 5m, 15m, 1h, 4h, or 1d.", true), object("filters", "One or more filter objects: pctChange, breakout, volumeSpike, smaCross, emaCross, rsi, rangeStats.", true)], { coin: "BTC", interval: "1h", filters: { rsi: { period: 14 }, volumeSpike: { window: 20, factor: "2" } } }),
  localWrite("hyperliquid.risk.proposeSetup", "Create a user-confirmable Hyperliquid session risk proposal; no trade is submitted.", [string("coin", "Core perp coin.", true), number("leverageCapDefault", "Proposed integer leverage cap.", true), number("perOrderNotionalPct", "Proposed per-order account-notional percent.", true), number("totalNotionalPct", "Proposed total account-notional percent.", true)], { coin: "BTC", leverageCapDefault: 3, perOrderNotionalPct: 20, totalNotionalPct: 100 }),
  mutate("hyperliquid.perp.open", "Open a Core perpetual. A stop-loss is mandatory unless the user explicitly disabled the Hyperliquid stop-loss policy.", [string("coin", "Core perp coin.", true), string("side", "long or short.", true), string("size", "Canonical decimal base size.", true), string("price", "Canonical decimal entry price.", true), string("slPrice", "Optional canonical stop-loss price; required by default policy."), string("tpPrice", "Optional canonical take-profit price."), number("leverage", "Integer leverage.", true), string("marginMode", "isolated or cross.", true), string("cloid", "Optional 0x client order id.")], { coin: "BTC", side: "long", size: "0.001", price: "60000", slPrice: "59000", leverage: 3, marginMode: "isolated" }),
  mutate("hyperliquid.perp.close", "Close/reduce a perpetual with a reduce-only IOC order.", [string("coin", "Core perp coin.", true), string("side", "buy or sell reduce-only order side.", true), string("size", "Canonical decimal size.", true), string("markPrice", "Canonical decimal mark price.", true), number("slippageBps", "Maximum IOC slippage basis points.", true), string("cloid", "Optional 0x client order id.")], { coin: "BTC", side: "sell", size: "0.001", markPrice: "60000", slippageBps: 50 }),
  mutate("hyperliquid.perp.setTpsl", "Replace a full-position stop safely.", [string("coin", "Core perp coin.", true), string("slPrice", "Canonical stop-loss price.", true)], { coin: "BTC", slPrice: "59000" }),
  mutate("hyperliquid.perp.modifyOrder", "Modify a perpetual order.", [string("coin", "Core perp coin.", true), number("oid", "Existing order id.", true), string("side", "buy or sell.", true), string("price", "Canonical decimal price.", true), string("size", "Canonical decimal size.", true), boolean("reduceOnly", "Retain reduce-only behavior.", true)], { coin: "BTC", oid: 1, side: "buy", price: "60000", size: "0.001", reduceOnly: false }),
  mutate("hyperliquid.perp.cancelOrders", "Cancel a named perpetual order while preserving sole protection.", [string("coin", "Core perp coin.", true), number("oid", "Order id to cancel.", true)], { coin: "BTC", oid: 1 }),
  mutate("hyperliquid.perp.setLeverage", "Set core-perp leverage within policy.", [string("coin", "Core perp coin.", true), number("leverage", "Integer leverage.", true), string("marginMode", "isolated or cross.", true)], { coin: "BTC", leverage: 3, marginMode: "isolated" }),
  mutate("hyperliquid.perp.adjustMargin", "Adjust isolated margin.", [string("coin", "Core perp coin.", true), string("side", "long or short position side.", true), number("ntli", "Signed isolated-margin adjustment integer.", true)], { coin: "BTC", side: "long", ntli: 10 }),
  mutate("hyperliquid.perp.twap", "Submit a protected Core perpetual TWAP.", [string("coin", "Core perp coin.", true), string("side", "buy or sell.", true), string("size", "Canonical decimal size.", true), number("minutes", "TWAP duration minutes.", true), boolean("randomize", "Randomize slice timing.")], { coin: "BTC", side: "buy", size: "0.001", minutes: 30 }),
  mutate("hyperliquid.spot.trade", "Place a Hyperliquid spot order.", [string("market", "Spot market name.", true), string("side", "buy or sell.", true), string("price", "Canonical decimal price.", true), string("size", "Canonical decimal size.", true), string("timeInForce", "Gtc, Ioc, Alo, or FrontendMarket.", true)], { market: "HYPE/USDC", side: "buy", price: "20", size: "1", timeInForce: "Ioc" }),
  walletBroadcast("hyperliquid.deposit", "Deposit native USDC from Arbitrum One to Hyperliquid's pinned Bridge2 contract. Deposits below 5 USDC are permanently lost.", [string("amountUsd", "Canonical native-USDC decimal amount; minimum 5 USDC.", true)], { amountUsd: "25" }),
  mutate("hyperliquid.transfer.usdClass", "Move USDC between Hyperliquid spot and perp accounts.", [string("amount", "Canonical USDC decimal amount.", true), boolean("toPerp", "True moves spot USDC to perp collateral.", true)], { amount: "25", toPerp: true }),
  mutate("hyperliquid.withdraw", "Withdraw Hyperliquid USDC to an external EVM address.", [string("destination", "Recipient EVM address.", true), string("amount", "Canonical USDC decimal amount.", true)], { destination: "0x0000000000000000000000000000000000000001", amount: "25" }),
  mutate("hyperliquid.transfer.send", "Send Hyperliquid USD or a spot token to an external EVM address.", [string("assetType", "usd or spot.", true), string("destination", "Recipient EVM address.", true), string("amount", "Canonical decimal amount.", true), string("token", "Required spot token symbol when assetType is spot.")], { assetType: "usd", destination: "0x0000000000000000000000000000000000000001", amount: "25" }),
  read("hyperliquid.vault.overview", "Show selected-wallet Hyperliquid vault and HLP equity positions."),
  mutate("hyperliquid.vault.transfer", "Deposit into or withdraw from a Hyperliquid vault, including HLP.", [string("vaultAddress", "Vault EVM address.", true), string("amount", "Canonical USDC decimal amount.", true), boolean("isDeposit", "True deposits, false withdraws.", true)], { vaultAddress: "0x0000000000000000000000000000000000000001", amount: "25", isDeposit: true }),
  read("hyperliquid.staking.overview", "Show selected-wallet Hyperliquid HYPE delegation and staking summary."),
  mutate("hyperliquid.staking.delegate", "Delegate or undelegate staked HYPE to a validator.", [string("validator", "Validator EVM address.", true), string("amountWei", "Canonical HYPE base-unit integer (1e8 units).", true), boolean("isUndelegate", "True undelegates, false delegates.", true)], { validator: "0x0000000000000000000000000000000000000001", amountWei: "100000000", isUndelegate: false }),
  mutate("hyperliquid.staking.transfer", "Move HYPE between spot and Hyperliquid staking balances.", [string("direction", "deposit or withdraw.", true), string("amountWei", "Canonical HYPE base-unit integer (1e8 units).", true)], { direction: "deposit", amountWei: "100000000" }),
  mutate("hyperliquid.rewards.claim", "Claim available Hyperliquid rewards." , [], {}),
  mutate("hyperliquid.builder.approveFee", "Approve the release-configured 0.025% Hyperliquid builder allowance; first-entry acknowledgment is the user disclosure.", [], {}),
  localPresentation("hyperliquid.workspace.enter", "Request the focused Hypervexing workspace. Main enforces the first-entry acknowledgment gate."),
  localPresentation("hyperliquid.workspace.exit", "Request a return to the normal Vex workspace."),
];
