import type { ProtocolToolManifest } from "../../types.js";
import { POLYMARKET_CLOB_DISCOVERY } from "../../embeddings/polymarket/clob.js";

export const CLOB_TOOLS: readonly ProtocolToolManifest[] = [
  // ── Market Data (public) ──────────────────────────────────────

  {
    toolId: "polymarket.clob.orderbook",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get full orderbook for a token — bids, asks, tick size, last trade price, neg risk flag.",
    mutating: false,
    params: [
      { key: "tokenId", type: "string", required: true, description: "CLOB token ID (outcome token asset ID)." },
    ],
    exampleParams: { tokenId: "71321..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.orderbook"],
  },
  {
    toolId: "polymarket.clob.orderbooks",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get orderbooks for multiple tokens in one call.",
    mutating: false,
    params: [
      { key: "tokenIds", type: "string", required: true, description: "Comma-separated CLOB token IDs." },
    ],
    exampleParams: { tokenIds: "71321...,82432..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.orderbooks"],
  },
  {
    toolId: "polymarket.clob.price",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get best available price for a token on BUY or SELL side.",
    mutating: false,
    params: [
      { key: "tokenId", type: "string", required: true, description: "CLOB token ID." },
      { key: "side", type: "string", required: true, description: "Side: BUY or SELL." },
    ],
    exampleParams: { tokenId: "71321...", side: "BUY" },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.price"],
  },
  {
    toolId: "polymarket.clob.prices",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get prices for multiple tokens and sides in one call.",
    mutating: false,
    params: [
      { key: "tokenIds", type: "string", required: true, description: "Comma-separated CLOB token IDs." },
      { key: "sides", type: "string", required: true, description: "Comma-separated sides (BUY/SELL) matching tokenIds order." },
    ],
    exampleParams: { tokenIds: "71321...,82432...", sides: "BUY,SELL" },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.prices"],
  },
  {
    toolId: "polymarket.clob.midpoint",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get midpoint price (average of best bid and best ask) for a token.",
    mutating: false,
    params: [
      { key: "tokenId", type: "string", required: true, description: "CLOB token ID." },
    ],
    exampleParams: { tokenId: "71321..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.midpoint"],
  },
  {
    toolId: "polymarket.clob.midpoints",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get midpoint prices for multiple tokens in one call.",
    mutating: false,
    params: [
      { key: "tokenIds", type: "string", required: true, description: "Comma-separated CLOB token IDs." },
    ],
    exampleParams: { tokenIds: "71321...,82432..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.midpoints"],
  },
  {
    toolId: "polymarket.clob.spread",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get bid-ask spread for a token.",
    mutating: false,
    params: [
      { key: "tokenId", type: "string", required: true, description: "CLOB token ID." },
    ],
    exampleParams: { tokenId: "71321..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.spread"],
  },
  {
    toolId: "polymarket.clob.spreads",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get spreads for multiple tokens in one call.",
    mutating: false,
    params: [
      { key: "tokenIds", type: "string", required: true, description: "Comma-separated CLOB token IDs." },
    ],
    exampleParams: { tokenIds: "71321...,82432..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.spreads"],
  },
  {
    toolId: "polymarket.clob.lastTrade",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get last trade price and side for a token.",
    mutating: false,
    params: [
      { key: "tokenId", type: "string", required: true, description: "CLOB token ID." },
    ],
    exampleParams: { tokenId: "71321..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.lastTrade"],
  },
  {
    toolId: "polymarket.clob.lastTrades",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get last trade prices for multiple tokens in one call.",
    mutating: false,
    params: [
      { key: "tokenIds", type: "string", required: true, description: "Comma-separated CLOB token IDs." },
    ],
    exampleParams: { tokenIds: "71321...,82432..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.lastTrades"],
  },
  {
    toolId: "polymarket.clob.priceHistory",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get price history time-series for a market — OHLC data with configurable interval and fidelity.",
    mutating: false,
    params: [
      { key: "market", type: "string", required: true, description: "Market condition ID." },
      { key: "interval", type: "string", description: "Time interval: 1h, 6h, 1d, 1w, 1m, all." },
      { key: "fidelity", type: "number", description: "Data point granularity in minutes." },
      { key: "startTs", type: "number", description: "Start timestamp (unix seconds)." },
      { key: "endTs", type: "number", description: "End timestamp (unix seconds)." },
    ],
    exampleParams: { market: "0xabc...", interval: "1d" },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.priceHistory"],
  },
  {
    toolId: "polymarket.clob.batchPriceHistory",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get price history for multiple markets in one call (max 20). POST endpoint.",
    mutating: false,
    params: [
      { key: "markets", type: "string", required: true, description: "Comma-separated market asset IDs (max 20)." },
      { key: "interval", type: "string", description: "Time interval: 1h, 6h, 1d, 1w, 1m, all, max." },
      { key: "fidelity", type: "number", description: "Data point granularity in minutes." },
      { key: "startTs", type: "number", description: "Start timestamp (unix seconds)." },
      { key: "endTs", type: "number", description: "End timestamp (unix seconds)." },
    ],
    exampleParams: { markets: "0xabc...,0xdef...", interval: "1d" },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.batchPriceHistory"],
  },
  {
    toolId: "polymarket.clob.serverTime",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get Polymarket CLOB server time (unix timestamp).",
    mutating: false,
    params: [],
    exampleParams: {},
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.serverTime"],
  },

  {
    toolId: "polymarket.clob.tickSize",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get minimum tick size (price increment) for a token.",
    mutating: false,
    params: [
      { key: "tokenId", type: "string", required: true, description: "CLOB token ID." },
    ],
    exampleParams: { tokenId: "71321..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.tickSize"],
  },
  {
    toolId: "polymarket.clob.feeRate",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get trading fee rate in basis points for a token.",
    mutating: false,
    params: [
      { key: "tokenId", type: "string", required: true, description: "CLOB token ID." },
    ],
    exampleParams: { tokenId: "71321..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.feeRate"],
  },

  // ── Trading (authenticated) ───────────────────────────────────

  {
    toolId: "polymarket.clob.buy",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Buy YES or NO outcome shares on Polymarket. Resolves market, builds EIP-712 signed order, submits to CLOB.",
    mutating: true,
    params: [
      { key: "conditionId", type: "string", required: true, description: "Market condition ID." },
      { key: "outcome", type: "string", required: true, description: "Outcome to buy: yes or no." },
      { key: "amount", type: "number", required: true, description: "Amount in USDC to spend." },
      { key: "price", type: "number", description: "Limit price (0-1). Omit for market order at best ask." },
      { key: "orderType", type: "string", description: "Order type: GTC, FOK, GTD, FAK (default: GTC)." },
      { key: "deferExec", type: "boolean", description: "Defer execution (default: false)." },
      { key: "dryRun", type: "boolean", description: "Preview order without submitting." },
    ],
    exampleParams: { conditionId: "0xabc...", outcome: "yes", amount: 10, price: 0.65 },
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.buy"],
  },
  {
    toolId: "polymarket.clob.sell",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Sell YES or NO outcome shares on Polymarket. EIP-712 signed order submitted to CLOB.",
    mutating: true,
    params: [
      { key: "conditionId", type: "string", required: true, description: "Market condition ID." },
      { key: "outcome", type: "string", required: true, description: "Outcome to sell: yes or no." },
      { key: "amount", type: "number", required: true, description: "Number of shares to sell." },
      { key: "price", type: "number", description: "Limit price (0-1). Omit for market order at best bid." },
      { key: "orderType", type: "string", description: "Order type: GTC, FOK, GTD, FAK (default: GTC)." },
      { key: "deferExec", type: "boolean", description: "Defer execution (default: false)." },
      { key: "dryRun", type: "boolean", description: "Preview order without submitting." },
    ],
    exampleParams: { conditionId: "0xabc...", outcome: "yes", amount: 10 },
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.sell"],
  },
  {
    toolId: "polymarket.clob.cancel",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Cancel a single open order by order ID.",
    mutating: true,
    params: [
      { key: "orderId", type: "string", required: true, description: "Order ID to cancel." },
    ],
    exampleParams: { orderId: "abc-123..." },
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.cancel"],
  },
  {
    toolId: "polymarket.clob.cancelAll",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Cancel all open orders on Polymarket.",
    mutating: true,
    params: [],
    exampleParams: {},
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.cancelAll"],
  },
  {
    toolId: "polymarket.clob.cancelMarket",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Cancel all open orders in a specific market.",
    mutating: true,
    params: [
      { key: "market", type: "string", required: true, description: "Market condition ID." },
      { key: "assetId", type: "string", required: true, description: "Asset/token ID." },
    ],
    exampleParams: { market: "0xabc...", assetId: "71321..." },
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.cancelMarket"],
  },
  {
    toolId: "polymarket.clob.orders",
    namespace: "polymarket",
    lifecycle: "active",
    description: "List open orders with optional market/asset filter. Paginated.",
    mutating: false,
    params: [
      { key: "id", type: "string", description: "Filter by specific order ID (hash)." },
      { key: "market", type: "string", description: "Filter by market condition ID." },
      { key: "assetId", type: "string", description: "Filter by asset/token ID." },
      { key: "cursor", type: "string", description: "Pagination cursor." },
    ],
    exampleParams: {},
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.orders"],
  },
  {
    toolId: "polymarket.clob.order",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get details of a single order by order ID.",
    mutating: false,
    params: [
      { key: "orderId", type: "string", required: true, description: "Order ID." },
    ],
    exampleParams: { orderId: "abc-123..." },
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.order"],
  },
  {
    toolId: "polymarket.clob.trades",
    namespace: "polymarket",
    lifecycle: "active",
    description: "List your CLOB trades with optional market/time filter. Paginated.",
    mutating: false,
    params: [
      { key: "id", type: "string", description: "Filter by specific trade ID." },
      { key: "market", type: "string", description: "Filter by market condition ID." },
      { key: "assetId", type: "string", description: "Filter by asset/token ID." },
      { key: "before", type: "string", description: "Filter trades before this unix timestamp." },
      { key: "after", type: "string", description: "Filter trades after this unix timestamp." },
      { key: "cursor", type: "string", description: "Pagination cursor." },
    ],
    exampleParams: {},
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.trades"],
  },
  {
    toolId: "polymarket.clob.simplifiedMarkets",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Lightweight paginated market list — condition_id, active/closed status, tokens with prices, rewards. Faster than full markets.",
    mutating: false,
    params: [
      { key: "cursor", type: "string", description: "Pagination cursor." },
    ],
    exampleParams: {},
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.simplifiedMarkets"],
  },
  {
    toolId: "polymarket.clob.rebates",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get current rebated fees for a maker address on a given date.",
    mutating: false,
    params: [
      { key: "date", type: "string", required: true, description: "Date in YYYY-MM-DD format." },
      { key: "makerAddress", type: "string", required: true, description: "Maker wallet address." },
    ],
    exampleParams: { date: "2026-04-04", makerAddress: "0x1234..." },
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.rebates"],
  },
  {
    toolId: "polymarket.clob.heartbeat",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Send heartbeat to keep automated orders alive. Orders auto-cancel if heartbeats stop.",
    mutating: true,
    params: [],
    exampleParams: {},
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.heartbeat"],
  },
  {
    toolId: "polymarket.clob.cancelOrders",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Cancel multiple orders by IDs in one call (max 3000).",
    mutating: true,
    params: [
      { key: "orderIds", type: "string", required: true, description: "Comma-separated order IDs to cancel." },
    ],
    exampleParams: { orderIds: "abc-123,def-456" },
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.cancelOrders"],
  },
  {
    toolId: "polymarket.clob.orderScoring",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Check if an order is being scored for rewards.",
    mutating: false,
    params: [
      { key: "orderId", type: "string", required: true, description: "Order ID." },
    ],
    exampleParams: { orderId: "abc-123..." },
    requiresEnv: "POLYMARKET_API_KEY",
    discovery: POLYMARKET_CLOB_DISCOVERY["polymarket.clob.orderScoring"],
  },
];
