import type { ProtocolToolManifest } from "../../types.js";
import { POLYMARKET_DATA_DISCOVERY } from "../../embeddings/polymarket/data.js";

export const DATA_TOOLS: readonly ProtocolToolManifest[] = [
  // ── User Data ─────────────────────────────────────────────────

  {
    toolId: "polymarket.data.positions",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get open prediction market positions — size, avgPrice, PnL, redeemable/mergeable status.",
    mutating: false,
    params: [
      { key: "user", type: "string", required: true, description: "User wallet or proxy address." },
      { key: "market", type: "string", description: "Filter by market condition ID." },
      { key: "eventId", type: "number", description: "Filter by event ID." },
      { key: "sizeThreshold", type: "number", description: "Min position size filter." },
      { key: "redeemable", type: "boolean", description: "Filter redeemable only." },
      { key: "mergeable", type: "boolean", description: "Filter mergeable only." },
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "sortBy", type: "string", description: "Sort: CURRENT, INITIAL, TOKENS, CASHPNL, PERCENTPNL, TITLE, RESOLVING, PRICE, AVGPRICE." },
      { key: "sortDirection", type: "string", description: "ASC or DESC." },
      { key: "title", type: "string", description: "Filter by title substring." },
    ],
    exampleParams: { user: "0x1234..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.positions"],
  },
  {
    toolId: "polymarket.data.closedPositions",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get closed prediction market positions with realized PnL.",
    mutating: false,
    params: [
      { key: "user", type: "string", required: true, description: "User wallet or proxy address." },
      { key: "market", type: "string", description: "Filter by market condition ID." },
      { key: "eventId", type: "number", description: "Filter by event ID." },
      { key: "title", type: "string", description: "Filter by title (max 100 chars)." },
      { key: "limit", type: "number", description: "Max results (default 10, max 50)." },
      { key: "offset", type: "number", description: "Pagination offset (max 100000)." },
      { key: "sortBy", type: "string", description: "Sort: REALIZEDPNL, TITLE, PRICE, AVGPRICE, TIMESTAMP." },
      { key: "sortDirection", type: "string", description: "ASC or DESC." },
    ],
    exampleParams: { user: "0x1234..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.closedPositions"],
  },
  {
    toolId: "polymarket.data.activity",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get user activity history — trades, splits, merges, redeems, rewards, conversions, maker rebates, referral rewards.",
    mutating: false,
    params: [
      { key: "user", type: "string", required: true, description: "User wallet or proxy address." },
      { key: "market", type: "string", description: "Filter by market condition ID (mutually exclusive with eventId)." },
      { key: "eventId", type: "number", description: "Filter by event ID (mutually exclusive with market)." },
      { key: "type", type: "string", description: "Filter: TRADE, SPLIT, MERGE, REDEEM, REWARD, CONVERSION, MAKER_REBATE, REFERRAL_REWARD." },
      { key: "side", type: "string", description: "Filter: BUY or SELL." },
      { key: "start", type: "number", description: "Filter after this unix timestamp." },
      { key: "end", type: "number", description: "Filter before this unix timestamp." },
      { key: "limit", type: "number", description: "Max results (default 100, max 500)." },
      { key: "offset", type: "number", description: "Pagination offset (max 10000)." },
      { key: "sortBy", type: "string", description: "Sort: TIMESTAMP, TOKENS, CASH." },
      { key: "sortDirection", type: "string", description: "ASC or DESC." },
    ],
    exampleParams: { user: "0x1234...", type: "TRADE", limit: 50 },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.activity"],
  },
  {
    toolId: "polymarket.data.trades",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get trades with tx hashes, prices, sizes — by user, market, or event.",
    mutating: false,
    params: [
      { key: "user", type: "string", description: "Filter by user address." },
      { key: "market", type: "string", description: "Filter by market condition ID (mutually exclusive with eventId)." },
      { key: "eventId", type: "number", description: "Filter by event ID (mutually exclusive with market)." },
      { key: "side", type: "string", description: "Filter: BUY or SELL." },
      { key: "takerOnly", type: "boolean", description: "Only taker trades (default: true)." },
      { key: "filterType", type: "string", description: "Filter by: CASH or TOKENS (requires filterAmount)." },
      { key: "filterAmount", type: "number", description: "Min amount for filterType." },
      { key: "limit", type: "number", description: "Max results (default 100, max 10000)." },
      { key: "offset", type: "number", description: "Pagination offset (max 10000)." },
    ],
    exampleParams: { user: "0x1234...", limit: 20 },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.trades"],
  },
  {
    toolId: "polymarket.data.value",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get total portfolio value in USD for a user.",
    mutating: false,
    params: [
      { key: "user", type: "string", required: true, description: "User wallet or proxy address." },
      { key: "market", type: "string", description: "Filter by specific market." },
    ],
    exampleParams: { user: "0x1234..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.value"],
  },
  {
    toolId: "polymarket.data.traded",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get total number of markets a user has traded in.",
    mutating: false,
    params: [
      { key: "user", type: "string", required: true, description: "User wallet or proxy address." },
    ],
    exampleParams: { user: "0x1234..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.traded"],
  },

  // ── Market Data ───────────────────────────────────────────────

  {
    toolId: "polymarket.data.holders",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get top holders per outcome token for a market — amounts, pseudonyms, profile images.",
    mutating: false,
    params: [
      { key: "market", type: "string", required: true, description: "Market condition ID." },
      { key: "limit", type: "number", description: "Max holders per token." },
      { key: "minBalance", type: "number", description: "Min balance filter." },
    ],
    exampleParams: { market: "0xabc..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.holders"],
  },
  {
    toolId: "polymarket.data.openInterest",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get open interest (total value locked) per market. Omit market for all.",
    mutating: false,
    params: [
      { key: "market", type: "string", description: "Market condition ID (optional — omit for all)." },
    ],
    exampleParams: { market: "0xabc..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.openInterest"],
  },
  {
    toolId: "polymarket.data.liveVolume",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get live trading volume for an event — total and per-market breakdown.",
    mutating: false,
    params: [
      { key: "eventId", type: "number", required: true, description: "Event ID." },
    ],
    exampleParams: { eventId: 12345 },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.liveVolume"],
  },
  {
    toolId: "polymarket.data.marketPositions",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get all positions in a specific market — per-user size, PnL, avgPrice.",
    mutating: false,
    params: [
      { key: "market", type: "string", required: true, description: "Market condition ID." },
      { key: "user", type: "string", description: "Filter by user." },
      { key: "status", type: "string", description: "Filter by status." },
      { key: "sortBy", type: "string", description: "Sort field." },
      { key: "sortDirection", type: "string", description: "ASC or DESC." },
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
    ],
    exampleParams: { market: "0xabc..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.marketPositions"],
  },

  // ── Leaderboard ───────────────────────────────────────────────

  {
    toolId: "polymarket.data.leaderboard",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get trader leaderboard ranked by PnL or volume. Filter by category, user, or username.",
    mutating: false,
    params: [
      { key: "category", type: "string", description: "Category: OVERALL, POLITICS, SPORTS, CRYPTO, CULTURE, MENTIONS, WEATHER, ECONOMICS, TECH, FINANCE." },
      { key: "timePeriod", type: "string", description: "Period: DAY, WEEK, MONTH, ALL." },
      { key: "orderBy", type: "string", description: "Rank by: PNL or VOL." },
      { key: "limit", type: "number", description: "Max entries (1-50, default 25)." },
      { key: "offset", type: "number", description: "Pagination offset (max 1000)." },
      { key: "user", type: "string", description: "Filter by trader wallet address." },
      { key: "userName", type: "string", description: "Filter by trader username." },
    ],
    exampleParams: { category: "OVERALL", timePeriod: "WEEK", limit: 20 },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.leaderboard"],
  },
  {
    toolId: "polymarket.data.builderLeaderboard",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get builder (API integrator) leaderboard by volume and active users.",
    mutating: false,
    params: [
      { key: "timePeriod", type: "string", description: "Period: DAY, WEEK, MONTH, ALL." },
      { key: "limit", type: "number", description: "Max entries." },
      { key: "offset", type: "number", description: "Pagination offset." },
    ],
    exampleParams: { timePeriod: "WEEK" },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.builderLeaderboard"],
  },
  {
    toolId: "polymarket.data.builderVolume",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get builder volume time-series — daily volume and active users per builder.",
    mutating: false,
    params: [
      { key: "timePeriod", type: "string", description: "Period: DAY, WEEK, MONTH, ALL." },
    ],
    exampleParams: { timePeriod: "WEEK" },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.builderVolume"],
  },

  // ── Accounting ────────────────────────────────────────────────

  {
    toolId: "polymarket.data.accountingSnapshot",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get URL for downloading full accounting snapshot (CSV) for a user.",
    mutating: false,
    params: [
      { key: "user", type: "string", required: true, description: "User wallet or proxy address." },
    ],
    exampleParams: { user: "0x1234..." },
    discovery: POLYMARKET_DATA_DISCOVERY["polymarket.data.accountingSnapshot"],
  },
];
