import type { ProtocolToolManifest } from "../../types.js";
import { POLYMARKET_GAMMA_DISCOVERY } from "../../embeddings/polymarket/gamma.js";

export const GAMMA_TOOLS: readonly ProtocolToolManifest[] = [
  // ── Events (4) ────────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.events",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Browse prediction market events — filter by tag, status, liquidity/volume bounds, date range. Includes nested markets with prices.",
    mutating: false,
    params: [
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field (e.g. volume24hr, liquidity, startDate)." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "slug", type: "string", description: "Filter by event slug(s), comma-separated." },
      { key: "tagSlug", type: "string", description: "Filter by tag slug." },
      { key: "tagId", type: "number", description: "Filter by tag ID." },
      { key: "excludeTagId", type: "string", description: "Exclude tag IDs, comma-separated." },
      { key: "relatedTags", type: "boolean", description: "Include related tags in response." },
      { key: "active", type: "boolean", description: "Filter active only." },
      { key: "closed", type: "boolean", description: "Filter closed only." },
      { key: "featured", type: "boolean", description: "Filter featured only." },
      { key: "archived", type: "boolean", description: "Filter archived events." },
      { key: "cyom", type: "boolean", description: "Filter create-your-own-market events." },
      { key: "liquidityMin", type: "number", description: "Minimum liquidity in USD." },
      { key: "liquidityMax", type: "number", description: "Maximum liquidity in USD." },
      { key: "volumeMin", type: "number", description: "Minimum volume in USD." },
      { key: "volumeMax", type: "number", description: "Maximum volume in USD." },
      { key: "startDateMin", type: "string", description: "Start date lower bound (ISO 8601)." },
      { key: "startDateMax", type: "string", description: "Start date upper bound (ISO 8601)." },
      { key: "endDateMin", type: "string", description: "End date lower bound (ISO 8601)." },
      { key: "endDateMax", type: "string", description: "End date upper bound (ISO 8601)." },
      { key: "recurrence", type: "string", description: "Filter by recurrence pattern." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { active: true, closed: false, liquidityMin: 1000, order: "volume24hr", ascending: false, limit: 10 },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.events"],
  },
  {
    toolId: "polymarket.gamma.event",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single event by ID — title, description, volume, liquidity, markets, tags.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Event ID." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { id: "12345" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.event"],
  },
  {
    toolId: "polymarket.gamma.eventBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single event by URL slug.",
    mutating: false,
    params: [
      { key: "slug", type: "string", required: true, description: "Event slug." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { slug: "will-bitcoin-hit-100k" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.eventBySlug"],
  },
  {
    toolId: "polymarket.gamma.eventTags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get tags associated with an event.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Event ID." },
    ],
    exampleParams: { id: "12345" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.eventTags"],
  },

  // ── Markets (4) ───────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.markets",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Browse prediction markets — filter by status, liquidity/volume bounds, date range, sports, tags. Includes prices, clobTokenIds.",
    mutating: false,
    params: [
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field (e.g. volume24hr, liquidityNum, endDate)." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "slug", type: "string", description: "Filter by slug(s), comma-separated." },
      { key: "clobTokenIds", type: "string", description: "Filter by CLOB token IDs, comma-separated." },
      { key: "conditionIds", type: "string", description: "Filter by condition IDs, comma-separated." },
      { key: "questionIds", type: "string", description: "Filter by question IDs, comma-separated." },
      { key: "closed", type: "boolean", description: "Filter by closed status." },
      { key: "tagId", type: "number", description: "Filter by tag ID." },
      { key: "relatedTags", type: "boolean", description: "Include related tags." },
      { key: "cyom", type: "boolean", description: "Create-your-own-market filter." },
      { key: "includeTag", type: "boolean", description: "Include tag data in response." },
      { key: "umaResolutionStatus", type: "string", description: "UMA resolution status filter." },
      { key: "liquidityMin", type: "number", description: "Min liquidity (USD)." },
      { key: "liquidityMax", type: "number", description: "Max liquidity (USD)." },
      { key: "volumeMin", type: "number", description: "Min volume (USD)." },
      { key: "volumeMax", type: "number", description: "Max volume (USD)." },
      { key: "startDateMin", type: "string", description: "Start date lower bound (ISO 8601)." },
      { key: "startDateMax", type: "string", description: "Start date upper bound (ISO 8601)." },
      { key: "endDateMin", type: "string", description: "End date lower bound (ISO 8601)." },
      { key: "endDateMax", type: "string", description: "End date upper bound (ISO 8601)." },
      { key: "gameId", type: "string", description: "Sports game ID filter." },
      { key: "sportsMarketTypes", type: "string", description: "Sports market types, comma-separated." },
      { key: "rewardsMinSize", type: "number", description: "Min rewards size." },
    ],
    exampleParams: { closed: false, liquidityMin: 1000, order: "volume24hr", ascending: false, limit: 10 },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.markets"],
  },
  {
    toolId: "polymarket.gamma.market",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single market by condition ID — question, outcomes, prices, clobTokenIds, negRisk.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Market condition ID or numeric ID." },
      { key: "includeTag", type: "boolean", description: "Include tag data." },
    ],
    exampleParams: { id: "0xabc..." },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.market"],
  },
  {
    toolId: "polymarket.gamma.marketBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single market by URL slug.",
    mutating: false,
    params: [
      { key: "slug", type: "string", required: true, description: "Market slug." },
      { key: "includeTag", type: "boolean", description: "Include tag data." },
    ],
    exampleParams: { slug: "will-eth-hit-5000" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.marketBySlug"],
  },
  {
    toolId: "polymarket.gamma.marketTags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get tags associated with a market.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Market condition ID." },
    ],
    exampleParams: { id: "0xabc..." },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.marketTags"],
  },

  // ── Search (1) ────────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.search",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Cross-entity search across events, tags, and profiles on Polymarket. Rich filtering and sorting.",
    mutating: false,
    params: [
      { key: "query", type: "string", required: true, description: "Search query." },
      { key: "limitPerType", type: "number", description: "Max results per entity type." },
      { key: "page", type: "number", description: "Page number." },
      { key: "eventsStatus", type: "string", description: "Filter events by status." },
      { key: "eventsTag", type: "string", description: "Filter by event tag(s), comma-separated." },
      { key: "excludeTagId", type: "string", description: "Exclude tag IDs, comma-separated." },
      { key: "sort", type: "string", description: "Sort results by field." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "keepClosedMarkets", type: "number", description: "Include closed markets (1=yes)." },
      { key: "searchTags", type: "boolean", description: "Include tags in results." },
      { key: "searchProfiles", type: "boolean", description: "Include profiles in results." },
      { key: "recurrence", type: "string", description: "Filter by recurrence pattern." },
      { key: "cache", type: "boolean", description: "Enable/disable caching." },
      { key: "optimized", type: "boolean", description: "Use optimized response format." },
    ],
    exampleParams: { query: "bitcoin", limitPerType: 5 },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.search"],
  },

  // ── Tags (7) ──────────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.tags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "List all tags (categories) on Polymarket with pagination and sorting.",
    mutating: false,
    params: [
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "isCarousel", type: "boolean", description: "Filter carousel tags only." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: {},
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tags"],
  },
  {
    toolId: "polymarket.gamma.tag",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single tag by ID.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Tag ID." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { id: "42" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tag"],
  },
  {
    toolId: "polymarket.gamma.tagBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single tag by slug.",
    mutating: false,
    params: [
      { key: "slug", type: "string", required: true, description: "Tag slug." },
      { key: "includeTemplate", type: "boolean", description: "Include template data." },
    ],
    exampleParams: { slug: "crypto" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tagBySlug"],
  },
  {
    toolId: "polymarket.gamma.relatedTags",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get related tag IDs for a tag by ID.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Tag ID." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { id: "42" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.relatedTags"],
  },
  {
    toolId: "polymarket.gamma.relatedTagsBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get related tag IDs for a tag by slug.",
    mutating: false,
    params: [
      { key: "slug", type: "string", required: true, description: "Tag slug." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { slug: "crypto" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.relatedTagsBySlug"],
  },
  {
    toolId: "polymarket.gamma.tagsRelatedToTag",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get full tag objects related to a tag by ID.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Tag ID." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { id: "42" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tagsRelatedToTag"],
  },
  {
    toolId: "polymarket.gamma.tagsRelatedToTagBySlug",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get full tag objects related to a tag by slug.",
    mutating: false,
    params: [
      { key: "slug", type: "string", required: true, description: "Tag slug." },
      { key: "status", type: "string", description: "Filter: active, closed, all." },
      { key: "omitEmpty", type: "boolean", description: "Exclude empty relationships." },
    ],
    exampleParams: { slug: "crypto" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.tagsRelatedToTagBySlug"],
  },

  // ── Series (2) ────────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.series",
    namespace: "polymarket",
    lifecycle: "active",
    description: "List event series — grouped recurring events. Filter by category, slug, recurrence.",
    mutating: false,
    params: [
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
      { key: "slug", type: "string", description: "Filter by slug(s), comma-separated." },
      { key: "closed", type: "boolean", description: "Filter by closed status." },
      { key: "categoriesIds", type: "string", description: "Filter by category IDs, comma-separated." },
      { key: "categoriesLabels", type: "string", description: "Filter by category labels, comma-separated." },
      { key: "recurrence", type: "string", description: "Filter by recurrence pattern." },
      { key: "excludeEvents", type: "boolean", description: "Exclude nested events from response." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
    ],
    exampleParams: {},
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.series"],
  },
  {
    toolId: "polymarket.gamma.seriesById",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single series by ID with nested events.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Series ID." },
      { key: "includeChat", type: "boolean", description: "Include chat data." },
    ],
    exampleParams: { id: "123" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.seriesById"],
  },

  // ── Comments (3) ──────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.comments",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Browse comments on Polymarket — filter by entity type, entity ID, holders only. Pagination and sorting.",
    mutating: false,
    params: [
      { key: "parentEntityType", type: "string", description: "Entity type: Event, Series, market." },
      { key: "parentEntityId", type: "number", description: "Entity ID." },
      { key: "holdersOnly", type: "boolean", description: "Only comments from token holders." },
      { key: "getPositions", type: "boolean", description: "Include position data." },
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
    ],
    exampleParams: { parentEntityType: "Event", parentEntityId: 12345 },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.comments"],
  },
  {
    toolId: "polymarket.gamma.comment",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get single comment by ID.",
    mutating: false,
    params: [
      { key: "id", type: "string", required: true, description: "Comment ID." },
      { key: "getPositions", type: "boolean", description: "Include position data." },
    ],
    exampleParams: { id: "789" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.comment"],
  },
  {
    toolId: "polymarket.gamma.commentsByUser",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get comments by a specific user address with pagination and sorting.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "User wallet address." },
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
    ],
    exampleParams: { address: "0x1234..." },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.commentsByUser"],
  },

  // ── Profiles (1) ──────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.profile",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get public profile — name, pseudonym, bio, X username, verified badge.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "User wallet address." },
    ],
    exampleParams: { address: "0x1234..." },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.profile"],
  },

  // ── Sports (3) ────────────────────────────────────────────────

  {
    toolId: "polymarket.gamma.sportsMetadata",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get sports categories metadata — sport names, images, resolutions.",
    mutating: false,
    params: [],
    exampleParams: {},
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.sportsMetadata"],
  },
  {
    toolId: "polymarket.gamma.sportsMarketTypes",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get available sports market types (e.g. moneyline, spread, total).",
    mutating: false,
    params: [],
    exampleParams: {},
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.sportsMarketTypes"],
  },
  {
    toolId: "polymarket.gamma.teams",
    namespace: "polymarket",
    lifecycle: "active",
    description: "List sports teams with league, record, logo. Filter by name or abbreviation.",
    mutating: false,
    params: [
      { key: "league", type: "string", description: "Filter by league (comma-separated for multiple)." },
      { key: "name", type: "string", description: "Filter by team name(s), comma-separated." },
      { key: "abbreviation", type: "string", description: "Filter by abbreviation(s), comma-separated." },
      { key: "limit", type: "number", description: "Max results." },
      { key: "offset", type: "number", description: "Pagination offset." },
      { key: "order", type: "string", description: "Sort field." },
      { key: "ascending", type: "boolean", description: "Ascending sort." },
    ],
    exampleParams: { league: "NBA" },
    discovery: POLYMARKET_GAMMA_DISCOVERY["polymarket.gamma.teams"],
  },
];
