import type { ProtocolToolManifest } from "../../types.js";

export const REWARDS_TOOLS: readonly ProtocolToolManifest[] = [
  // ── Public ───────────────────────────────────────────────────────

  {
    toolId: "polymarket.rewards.active",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get current active reward configurations — daily rates, min size, max spread per market. Paginated.",
    mutating: false,
    params: [
      { key: "sponsored", type: "boolean", description: "Return sponsored configs instead of standard." },
      { key: "cursor", type: "string", description: "Pagination cursor." },
    ],
    exampleParams: {},
  },
  {
    toolId: "polymarket.rewards.market",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get raw reward configs for a specific market — rates, competitiveness, token prices.",
    mutating: false,
    params: [
      { key: "conditionId", type: "string", required: true, description: "Market condition ID." },
      { key: "sponsored", type: "boolean", description: "Fold sponsored rates into config." },
      { key: "cursor", type: "string", description: "Pagination cursor." },
    ],
    exampleParams: { conditionId: "0xabc..." },
  },
  {
    toolId: "polymarket.rewards.multi",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Search markets with rewards — filter by tag, volume, spread, price. Rich sorting options.",
    mutating: false,
    params: [
      { key: "query", type: "string", description: "Text search on question/description." },
      { key: "tagSlug", type: "string", description: "Filter by tag slug." },
      { key: "eventId", type: "string", description: "Filter by event ID." },
      { key: "eventTitle", type: "string", description: "Search event titles." },
      { key: "orderBy", type: "string", description: "Sort: volume_24hr, spread, competitiveness, rate_per_day, price, end_date, etc." },
      { key: "position", type: "string", description: "Sort direction: ASC or DESC." },
      { key: "minVolume24hr", type: "number", description: "Min 24h volume." },
      { key: "maxVolume24hr", type: "number", description: "Max 24h volume." },
      { key: "minSpread", type: "number", description: "Min spread." },
      { key: "maxSpread", type: "number", description: "Max spread." },
      { key: "minPrice", type: "number", description: "Min first token price." },
      { key: "maxPrice", type: "number", description: "Max first token price." },
      { key: "cursor", type: "string", description: "Pagination cursor." },
      { key: "pageSize", type: "number", description: "Items per page (max 500)." },
    ],
    exampleParams: { orderBy: "rate_per_day", position: "DESC", pageSize: 20 },
  },

  // ── Authenticated ────────────────────────────────────────────────

  {
    toolId: "polymarket.rewards.earnings",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get your reward earnings per market for a specific date. Paginated.",
    mutating: false,
    params: [
      { key: "date", type: "string", required: true, description: "Date in YYYY-MM-DD format." },
      { key: "signatureType", type: "number", description: "Address type: 0=EOA, 1=POLY_PROXY, 2=GNOSIS_SAFE." },
      { key: "makerAddress", type: "string", description: "Override maker address." },
      { key: "sponsored", type: "boolean", description: "Return only sponsored earnings." },
      { key: "cursor", type: "string", description: "Pagination cursor." },
    ],
    exampleParams: { date: "2026-04-04" },
    requiresEnv: "POLYMARKET_API_KEY",
  },
  {
    toolId: "polymarket.rewards.totalEarnings",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get total aggregated reward earnings for a date (all markets combined).",
    mutating: false,
    params: [
      { key: "date", type: "string", required: true, description: "Date in YYYY-MM-DD format." },
      { key: "signatureType", type: "number", description: "Address type: 0=EOA, 1=POLY_PROXY, 2=GNOSIS_SAFE." },
      { key: "makerAddress", type: "string", description: "Override maker address." },
      { key: "sponsored", type: "boolean", description: "Aggregate native + sponsored earnings." },
    ],
    exampleParams: { date: "2026-04-04" },
    requiresEnv: "POLYMARKET_API_KEY",
  },
  {
    toolId: "polymarket.rewards.percentages",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get your reward percentage share per market — shows what % of rewards you earn.",
    mutating: false,
    params: [
      { key: "signatureType", type: "number", description: "Address type: 0=EOA, 1=POLY_PROXY, 2=GNOSIS_SAFE." },
      { key: "makerAddress", type: "string", description: "Override maker address." },
    ],
    exampleParams: {},
    requiresEnv: "POLYMARKET_API_KEY",
  },
  {
    toolId: "polymarket.rewards.userMarkets",
    namespace: "polymarket",
    lifecycle: "active",
    description: "Get your earnings combined with market configs — search, filter, paginate. Full reward dashboard.",
    mutating: false,
    params: [
      { key: "date", type: "string", description: "Date (YYYY-MM-DD, default: today)." },
      { key: "signatureType", type: "number", description: "Address type: 0=EOA, 1=POLY_PROXY, 2=GNOSIS_SAFE." },
      { key: "makerAddress", type: "string", description: "Override maker address." },
      { key: "sponsored", type: "boolean", description: "Include sponsored earnings." },
      { key: "query", type: "string", description: "Search by question/description." },
      { key: "tagSlug", type: "string", description: "Filter by tag slug." },
      { key: "orderBy", type: "string", description: "Sort field." },
      { key: "position", type: "string", description: "Sort direction: ASC or DESC." },
      { key: "cursor", type: "string", description: "Pagination cursor." },
      { key: "pageSize", type: "number", description: "Items per page (max 500)." },
    ],
    exampleParams: { orderBy: "rate_per_day", position: "DESC" },
    requiresEnv: "POLYMARKET_API_KEY",
  },
];
