/**
 * Structured error class for Echo CLI.
 * Enables consistent JSON error output for automation.
 */
export class EchoError extends Error {
  retryable?: boolean;
  externalName?: string;

  constructor(
    public readonly code: string,
    message: string,
    public readonly hint?: string
  ) {
    super(message);
    this.name = "EchoError";
  }
}

/**
 * Standard error codes for automation consumers.
 */
export const ErrorCodes = {
  // Wallet & Config
  KEYSTORE_PASSWORD_NOT_SET: "KEYSTORE_PASSWORD_NOT_SET",
  WALLET_NOT_CONFIGURED: "WALLET_NOT_CONFIGURED",
  KEYSTORE_NOT_FOUND: "KEYSTORE_NOT_FOUND",
  KEYSTORE_ALREADY_EXISTS: "KEYSTORE_ALREADY_EXISTS",
  KEYSTORE_DECRYPT_FAILED: "KEYSTORE_DECRYPT_FAILED",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  INTENT_NOT_FOUND: "INTENT_NOT_FOUND",
  INTENT_EXPIRED: "INTENT_EXPIRED",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  INVALID_ADDRESS: "INVALID_ADDRESS",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  CHAIN_MISMATCH: "CHAIN_MISMATCH",
  RPC_ERROR: "RPC_ERROR",
  SIGNER_MISMATCH: "SIGNER_MISMATCH",
  INTERACTIVE_COMMAND_NOT_SUPPORTED: "INTERACTIVE_COMMAND_NOT_SUPPORTED",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  // Jaine DEX
  POOL_NOT_FOUND: "POOL_NOT_FOUND",
  NO_ROUTE_FOUND: "NO_ROUTE_FOUND",
  QUOTE_FAILED: "QUOTE_FAILED",
  APPROVAL_FAILED: "APPROVAL_FAILED",
  SWAP_FAILED: "SWAP_FAILED",
  SLIPPAGE_EXCEEDED: "SLIPPAGE_EXCEEDED",
  POSITION_NOT_FOUND: "POSITION_NOT_FOUND",
  LP_OPERATION_FAILED: "LP_OPERATION_FAILED",
  INVALID_FEE_TIER: "INVALID_FEE_TIER",
  INVALID_SLIPPAGE: "INVALID_SLIPPAGE",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  INVALID_SPENDER: "INVALID_SPENDER",

  // Slop.money
  SLOP_TOKEN_NOT_OFFICIAL: "SLOP_TOKEN_NOT_OFFICIAL",
  SLOP_TOKEN_GRADUATED: "SLOP_TOKEN_GRADUATED",
  SLOP_TRADE_DISABLED: "SLOP_TRADE_DISABLED",
  SLOP_QUOTE_FAILED: "SLOP_QUOTE_FAILED",
  SLOP_TX_FAILED: "SLOP_TX_FAILED",
  SLOP_INSUFFICIENT_BALANCE: "SLOP_INSUFFICIENT_BALANCE",
  SLOP_CREATE_FAILED: "SLOP_CREATE_FAILED",

  // Profile
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_ALREADY_EXISTS: "PROFILE_ALREADY_EXISTS",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  INVALID_USERNAME: "INVALID_USERNAME",
  NONCE_EXPIRED: "NONCE_EXPIRED",
  SIGNATURE_FAILED: "SIGNATURE_FAILED",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",

  // Image
  IMAGE_UPLOAD_FAILED: "IMAGE_UPLOAD_FAILED",
  IMAGE_TOO_LARGE: "IMAGE_TOO_LARGE",
  IMAGE_INVALID_FORMAT: "IMAGE_INVALID_FORMAT",
  IMAGE_GENERATION_FAILED: "IMAGE_GENERATION_FAILED",

  // Chat
  CHAT_NOT_AUTHENTICATED: "CHAT_NOT_AUTHENTICATED",
  CHAT_SESSION_EXPIRED: "CHAT_SESSION_EXPIRED",
  CHAT_RATE_LIMITED: "CHAT_RATE_LIMITED",
  CHAT_MESSAGE_EMPTY: "CHAT_MESSAGE_EMPTY",
  CHAT_MESSAGE_TOO_LONG: "CHAT_MESSAGE_TOO_LONG",
  CHAT_SEND_FAILED: "CHAT_SEND_FAILED",

  // Agents
  AGENT_QUERY_FAILED: "AGENT_QUERY_FAILED",
  AGENT_QUERY_TIMEOUT: "AGENT_QUERY_TIMEOUT",
  AGENT_QUERY_INVALID: "AGENT_QUERY_INVALID",

  // Echo Agent daemon
  AGENT_START_FAILED: "AGENT_START_FAILED",
  AGENT_NOT_RUNNING: "AGENT_NOT_RUNNING",

  // Echo Agent runtime
  AGENT_VALIDATION_ERROR: "AGENT_VALIDATION_ERROR",
  AGENT_INFERENCE_FAILED: "AGENT_INFERENCE_FAILED",
  AGENT_TOOL_EXECUTION_FAILED: "AGENT_TOOL_EXECUTION_FAILED",
  AGENT_COMPACTION_FAILED: "AGENT_COMPACTION_FAILED",
  AGENT_APPROVAL_NOT_FOUND: "AGENT_APPROVAL_NOT_FOUND",
  AGENT_SCHEDULER_FAILED: "AGENT_SCHEDULER_FAILED",
  AGENT_BACKUP_FAILED: "AGENT_BACKUP_FAILED",
  AGENT_RESTORE_FAILED: "AGENT_RESTORE_FAILED",
  AGENT_EXTERNAL_SERVICE_FAILED: "AGENT_EXTERNAL_SERVICE_FAILED",

  // Slop Auth (JWT)
  SLOP_AUTH_FAILED: "SLOP_AUTH_FAILED",
  SLOP_TOKEN_EXPIRED: "SLOP_TOKEN_EXPIRED",
  SLOP_REFRESH_FAILED: "SLOP_REFRESH_FAILED",

  // EchoBook
  ECHOBOOK_AUTH_REQUIRED: "ECHOBOOK_AUTH_REQUIRED",
  ECHOBOOK_AUTH_FAILED: "ECHOBOOK_AUTH_FAILED",
  ECHOBOOK_JWT_EXPIRED: "ECHOBOOK_JWT_EXPIRED",
  ECHOBOOK_POST_FAILED: "ECHOBOOK_POST_FAILED",
  ECHOBOOK_COMMENT_FAILED: "ECHOBOOK_COMMENT_FAILED",
  ECHOBOOK_VOTE_FAILED: "ECHOBOOK_VOTE_FAILED",
  ECHOBOOK_FOLLOW_FAILED: "ECHOBOOK_FOLLOW_FAILED",
  ECHOBOOK_TRADE_PROOF_FAILED: "ECHOBOOK_TRADE_PROOF_FAILED",
  ECHOBOOK_NOTIFICATIONS_FAILED: "ECHOBOOK_NOTIFICATIONS_FAILED",
  ECHOBOOK_NOT_FOUND: "ECHOBOOK_NOT_FOUND",
  ECHOBOOK_REPOST_FAILED: "ECHOBOOK_REPOST_FAILED",
  ECHOBOOK_OWNERSHIP_FAILED: "ECHOBOOK_OWNERSHIP_FAILED",

  // ChainScan
  CHAINSCAN_API_ERROR: "CHAINSCAN_API_ERROR",
  CHAINSCAN_RATE_LIMITED: "CHAINSCAN_RATE_LIMITED",
  CHAINSCAN_TIMEOUT: "CHAINSCAN_TIMEOUT",
  CHAINSCAN_INVALID_RESPONSE: "CHAINSCAN_INVALID_RESPONSE",
  CHAINSCAN_NO_RESULT: "CHAINSCAN_NO_RESULT",

  // Jaine Subgraph
  SUBGRAPH_API_ERROR: "SUBGRAPH_API_ERROR",
  SUBGRAPH_RATE_LIMITED: "SUBGRAPH_RATE_LIMITED",
  SUBGRAPH_TIMEOUT: "SUBGRAPH_TIMEOUT",
  SUBGRAPH_INVALID_RESPONSE: "SUBGRAPH_INVALID_RESPONSE",

  // HTTP
  HTTP_REQUEST_FAILED: "HTTP_REQUEST_FAILED",
  HTTP_TIMEOUT: "HTTP_TIMEOUT",

  // Khalani / HyperStream
  KHALANI_API_ERROR: "KHALANI_API_ERROR",
  KHALANI_TIMEOUT: "KHALANI_TIMEOUT",
  KHALANI_RATE_LIMITED: "KHALANI_RATE_LIMITED",
  KHALANI_QUOTE_NOT_FOUND: "KHALANI_QUOTE_NOT_FOUND",
  KHALANI_QUOTE_EXPIRED: "KHALANI_QUOTE_EXPIRED",
  KHALANI_VALIDATION_ERROR: "KHALANI_VALIDATION_ERROR",
  KHALANI_CANNOT_FILL: "KHALANI_CANNOT_FILL",
  KHALANI_UNSUPPORTED_TOKEN: "KHALANI_UNSUPPORTED_TOKEN",
  KHALANI_UNSUPPORTED_CHAIN: "KHALANI_UNSUPPORTED_CHAIN",
  KHALANI_DEPOSIT_FAILED: "KHALANI_DEPOSIT_FAILED",
  KHALANI_BROADCAST_FAILED: "KHALANI_BROADCAST_FAILED",
  KHALANI_PERMIT2_BLOCKED: "KHALANI_PERMIT2_BLOCKED",
  KHALANI_ORDER_NOT_FOUND: "KHALANI_ORDER_NOT_FOUND",
  KHALANI_SOLANA_SIGN_FAILED: "KHALANI_SOLANA_SIGN_FAILED",
  KHALANI_SOLANA_KEYSTORE_NOT_FOUND: "KHALANI_SOLANA_KEYSTORE_NOT_FOUND",
  KHALANI_ADDRESS_MISMATCH: "KHALANI_ADDRESS_MISMATCH",
  KHALANI_UNSUPPORTED_DEPOSIT_METHOD: "KHALANI_UNSUPPORTED_DEPOSIT_METHOD",

  // KyberSwap — shared
  KYBER_API_ERROR: "KYBER_API_ERROR",
  KYBER_TIMEOUT: "KYBER_TIMEOUT",
  KYBER_RATE_LIMITED: "KYBER_RATE_LIMITED",
  KYBER_UNSUPPORTED_CHAIN: "KYBER_UNSUPPORTED_CHAIN",

  // KyberSwap Aggregator
  KYBER_ROUTE_NOT_FOUND: "KYBER_ROUTE_NOT_FOUND",
  KYBER_TOKEN_NOT_FOUND: "KYBER_TOKEN_NOT_FOUND",
  KYBER_BUILD_FAILED: "KYBER_BUILD_FAILED",
  KYBER_MALFORMED_PARAMS: "KYBER_MALFORMED_PARAMS",
  KYBER_FEE_EXCEEDS_AMOUNT: "KYBER_FEE_EXCEEDS_AMOUNT",
  KYBER_AMOUNT_TOO_LARGE: "KYBER_AMOUNT_TOO_LARGE",
  KYBER_WETH_NOT_CONFIGURED: "KYBER_WETH_NOT_CONFIGURED",

  // KyberSwap Token API
  KYBER_TOKEN_SEARCH_FAILED: "KYBER_TOKEN_SEARCH_FAILED",
  KYBER_HONEYPOT_CHECK_FAILED: "KYBER_HONEYPOT_CHECK_FAILED",

  // KyberSwap Limit Orders
  KYBER_LO_SIGN_FAILED: "KYBER_LO_SIGN_FAILED",
  KYBER_LO_CREATE_FAILED: "KYBER_LO_CREATE_FAILED",
  KYBER_LO_CANCEL_FAILED: "KYBER_LO_CANCEL_FAILED",
  KYBER_LO_FILL_FAILED: "KYBER_LO_FILL_FAILED",
  KYBER_LO_ORDER_NOT_FOUND: "KYBER_LO_ORDER_NOT_FOUND",
  KYBER_LO_INSUFFICIENT_ALLOWANCE: "KYBER_LO_INSUFFICIENT_ALLOWANCE",
  KYBER_LO_SIGNATURE_INVALID: "KYBER_LO_SIGNATURE_INVALID",

  // KyberSwap ZaaS
  KYBER_ZAP_ROUTE_NOT_FOUND: "KYBER_ZAP_ROUTE_NOT_FOUND",
  KYBER_ZAP_BUILD_FAILED: "KYBER_ZAP_BUILD_FAILED",
  KYBER_ZAP_UNSUPPORTED_DEX: "KYBER_ZAP_UNSUPPORTED_DEX",
  KYBER_ZAP_INVALID_POSITION: "KYBER_ZAP_INVALID_POSITION",

  // Polymarket
  POLYMARKET_API_ERROR: "POLYMARKET_API_ERROR",
  POLYMARKET_TIMEOUT: "POLYMARKET_TIMEOUT",
  POLYMARKET_RATE_LIMITED: "POLYMARKET_RATE_LIMITED",
  POLYMARKET_AUTH_FAILED: "POLYMARKET_AUTH_FAILED",
  POLYMARKET_ORDER_FAILED: "POLYMARKET_ORDER_FAILED",
  POLYMARKET_ORDER_NOT_FOUND: "POLYMARKET_ORDER_NOT_FOUND",
  POLYMARKET_MARKET_NOT_FOUND: "POLYMARKET_MARKET_NOT_FOUND",
  POLYMARKET_INSUFFICIENT_BALANCE: "POLYMARKET_INSUFFICIENT_BALANCE",
  POLYMARKET_NOT_CONFIGURED: "POLYMARKET_NOT_CONFIGURED",

  // Setup
  SETUP_TARGET_EXISTS: "SETUP_TARGET_EXISTS",
  SETUP_LINK_FAILED: "SETUP_LINK_FAILED",
  SETUP_SOURCE_NOT_FOUND: "SETUP_SOURCE_NOT_FOUND",

  // Openclaw
  OPENCLAW_CONFIG_WRITE_FAILED: "OPENCLAW_CONFIG_WRITE_FAILED",
  OPENCLAW_CONFIG_PARSE_FAILED: "OPENCLAW_CONFIG_PARSE_FAILED",
  OPENCLAW_HOOKS_VALIDATION_FAILED: "OPENCLAW_HOOKS_VALIDATION_FAILED",
  OPENCLAW_HOOKS_TOKEN_MISMATCH: "OPENCLAW_HOOKS_TOKEN_MISMATCH",
  OPENCLAW_HOOKS_PROBE_FAILED: "OPENCLAW_HOOKS_PROBE_FAILED",

  KEYSTORE_CORRUPT: "KEYSTORE_CORRUPT",

  // Wallet import/export
  INVALID_PRIVATE_KEY: "INVALID_PRIVATE_KEY",
  EXPORT_BLOCKED_HEADLESS: "EXPORT_BLOCKED_HEADLESS",
  EXPORT_REQUIRES_ACKNOWLEDGE: "EXPORT_REQUIRES_ACKNOWLEDGE",

  // Backup
  BACKUP_NOT_FOUND: "BACKUP_NOT_FOUND",
  BACKUP_CREATE_FAILED: "BACKUP_CREATE_FAILED",
  AUTO_BACKUP_FAILED: "AUTO_BACKUP_FAILED",

  // Bot
  BOT_ALREADY_RUNNING: "BOT_ALREADY_RUNNING",
  BOT_NOT_RUNNING: "BOT_NOT_RUNNING",
  BOT_ORDER_NOT_FOUND: "BOT_ORDER_NOT_FOUND",
  BOT_INVALID_TRIGGER: "BOT_INVALID_TRIGGER",
  BOT_INVALID_ORDER: "BOT_INVALID_ORDER",
  BOT_STREAM_FAILED: "BOT_STREAM_FAILED",
  BOT_TRADE_FAILED: "BOT_TRADE_FAILED",
  BOT_GUARDRAIL_EXCEEDED: "BOT_GUARDRAIL_EXCEEDED",

  // 0G Compute
  ZG_BROKER_INIT_FAILED: "ZG_BROKER_INIT_FAILED",
  ZG_PROVIDER_NOT_FOUND: "ZG_PROVIDER_NOT_FOUND",
  ZG_LEDGER_NOT_FOUND: "ZG_LEDGER_NOT_FOUND",
  ZG_INSUFFICIENT_BALANCE: "ZG_INSUFFICIENT_BALANCE",
  ZG_ACKNOWLEDGE_FAILED: "ZG_ACKNOWLEDGE_FAILED",
  ZG_API_KEY_FAILED: "ZG_API_KEY_FAILED",
  ZG_TRANSFER_FAILED: "ZG_TRANSFER_FAILED",
  ZG_MONITOR_ALREADY_RUNNING: "ZG_MONITOR_ALREADY_RUNNING",
  ZG_MONITOR_NOT_RUNNING: "ZG_MONITOR_NOT_RUNNING",

  // Update Daemon
  UPDATE_DAEMON_ALREADY_RUNNING: "UPDATE_DAEMON_ALREADY_RUNNING",
  UPDATE_DAEMON_NOT_RUNNING: "UPDATE_DAEMON_NOT_RUNNING",
  ZG_ACK_TIMEOUT: "ZG_ACK_TIMEOUT",
  ZG_READINESS_CHECK_FAILED: "ZG_READINESS_CHECK_FAILED",
  ZG_INSUFFICIENT_WALLET_BALANCE: "ZG_INSUFFICIENT_WALLET_BALANCE",

  // Guardrails
  WALLET_MUTATION_BLOCKED_HEADLESS: "WALLET_MUTATION_BLOCKED_HEADLESS",

  // Onboard
  ONBOARD_REQUIRES_TTY: "ONBOARD_REQUIRES_TTY",

  // Claude Proxy
  CLAUDE_PROXY_ALREADY_RUNNING: "CLAUDE_PROXY_ALREADY_RUNNING",
  CLAUDE_PROXY_NOT_RUNNING: "CLAUDE_PROXY_NOT_RUNNING",
  CLAUDE_PROXY_START_FAILED: "CLAUDE_PROXY_START_FAILED",
  CLAUDE_CONFIG_PARSE_FAILED: "CLAUDE_CONFIG_PARSE_FAILED",
  CLAUDE_CONFIG_WRITE_FAILED: "CLAUDE_CONFIG_WRITE_FAILED",
  CLAUDE_CONFIG_RESTORE_FAILED: "CLAUDE_CONFIG_RESTORE_FAILED",
  CLAUDE_CONFIG_NOT_CONFIGURED: "CLAUDE_CONFIG_NOT_CONFIGURED",

  // Launcher
  LAUNCHER_START_FAILED: "LAUNCHER_START_FAILED",
  LAUNCHER_NOT_RUNNING: "LAUNCHER_NOT_RUNNING",

  // 0G Storage
  ZG_STORAGE_SETUP_FAILED: "ZG_STORAGE_SETUP_FAILED",
  ZG_STORAGE_UPLOAD_FAILED: "ZG_STORAGE_UPLOAD_FAILED",
  ZG_STORAGE_DOWNLOAD_FAILED: "ZG_STORAGE_DOWNLOAD_FAILED",
  ZG_STORAGE_FILE_NOT_FOUND: "ZG_STORAGE_FILE_NOT_FOUND",
  ZG_STORAGE_INDEX_NOT_FOUND: "ZG_STORAGE_INDEX_NOT_FOUND",
  ZG_STORAGE_INDEX_CONFLICT: "ZG_STORAGE_INDEX_CONFLICT",
  ZG_STORAGE_INVALID_PATH: "ZG_STORAGE_INVALID_PATH",
  ZG_STORAGE_PERMISSION_DENIED: "ZG_STORAGE_PERMISSION_DENIED",

  // Solana
  SOLANA_INVALID_ADDRESS: "SOLANA_INVALID_ADDRESS",
  SOLANA_INSUFFICIENT_BALANCE: "SOLANA_INSUFFICIENT_BALANCE",
  SOLANA_TRANSFER_FAILED: "SOLANA_TRANSFER_FAILED",
  SOLANA_TX_FAILED: "SOLANA_TX_FAILED",
  SOLANA_TX_TIMEOUT: "SOLANA_TX_TIMEOUT",
  SOLANA_TOKEN_NOT_FOUND: "SOLANA_TOKEN_NOT_FOUND",
  SOLANA_RPC_ERROR: "SOLANA_RPC_ERROR",
  SOLANA_QUOTE_FAILED: "SOLANA_QUOTE_FAILED",
  SOLANA_SWAP_FAILED: "SOLANA_SWAP_FAILED",
  SOLANA_STAKE_FAILED: "SOLANA_STAKE_FAILED",
  SOLANA_ORDER_FAILED: "SOLANA_ORDER_FAILED",


  // Jupiter Portfolio
  SOLANA_PORTFOLIO_FAILED: "SOLANA_PORTFOLIO_FAILED",

  // Jupiter Lend
  SOLANA_LEND_DEPOSIT_FAILED: "SOLANA_LEND_DEPOSIT_FAILED",
  SOLANA_LEND_WITHDRAW_FAILED: "SOLANA_LEND_WITHDRAW_FAILED",
  SOLANA_LEND_RATES_FAILED: "SOLANA_LEND_RATES_FAILED",

  // Jupiter Send
  SOLANA_SEND_INVITE_FAILED: "SOLANA_SEND_INVITE_FAILED",
  SOLANA_SEND_CLAWBACK_FAILED: "SOLANA_SEND_CLAWBACK_FAILED",

  // Jupiter Prediction
  SOLANA_PREDICT_ORDER_FAILED: "SOLANA_PREDICT_ORDER_FAILED",
  SOLANA_PREDICT_CLAIM_FAILED: "SOLANA_PREDICT_CLAIM_FAILED",

  // Jupiter Studio
  SOLANA_STUDIO_CREATE_FAILED: "SOLANA_STUDIO_CREATE_FAILED",
  SOLANA_STUDIO_CLAIM_FAILED: "SOLANA_STUDIO_CLAIM_FAILED",

  // Solana LP
  SOLANA_LP_POOL_NOT_FOUND: "SOLANA_LP_POOL_NOT_FOUND",
  SOLANA_LP_POSITION_NOT_FOUND: "SOLANA_LP_POSITION_NOT_FOUND",
  SOLANA_LP_DEPOSIT_FAILED: "SOLANA_LP_DEPOSIT_FAILED",
  SOLANA_LP_WITHDRAW_FAILED: "SOLANA_LP_WITHDRAW_FAILED",
  SOLANA_LP_CLAIM_FAILED: "SOLANA_LP_CLAIM_FAILED",

  // DexScreener
  DEXSCREENER_API_ERROR: "DEXSCREENER_API_ERROR",
  DEXSCREENER_RATE_LIMITED: "DEXSCREENER_RATE_LIMITED",
  DEXSCREENER_TIMEOUT: "DEXSCREENER_TIMEOUT",
  DEXSCREENER_INVALID_RESPONSE: "DEXSCREENER_INVALID_RESPONSE",
  DEXSCREENER_NOT_FOUND: "DEXSCREENER_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
