/**
 * Structured error class for Vex runtime and automation.
 */
export class VexError extends Error {
  retryable?: boolean;
  externalName?: string;

  constructor(
    public readonly code: string,
    message: string,
    public readonly hint?: string
  ) {
    super(message);
    this.name = "VexError";
  }
}

/**
 * Standard error codes for automation consumers.
 */
export const ErrorCodes = {
  // Wallet & Config
  KEYSTORE_PASSWORD_NOT_SET: "KEYSTORE_PASSWORD_NOT_SET",
  WALLET_NOT_CONFIGURED: "WALLET_NOT_CONFIGURED",
  KEYSTORE_NOT_FOUND: "KEYSTORE_NOT_FOUND",
  KEYSTORE_ALREADY_EXISTS: "KEYSTORE_ALREADY_EXISTS",
  KEYSTORE_DECRYPT_FAILED: "KEYSTORE_DECRYPT_FAILED",
  // Multi-wallet inventory (puzzle 5 stage 1)
  WALLET_INVENTORY_FULL: "WALLET_INVENTORY_FULL",
  WALLET_DUPLICATE_ADDRESS: "WALLET_DUPLICATE_ADDRESS",
  WALLET_ID_INVALID: "WALLET_ID_INVALID",
  WALLET_NOT_SELECTED: "WALLET_NOT_SELECTED",
  WALLET_SCOPE_MISMATCH: "WALLET_SCOPE_MISMATCH",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  INTENT_NOT_FOUND: "INTENT_NOT_FOUND",
  INTENT_EXPIRED: "INTENT_EXPIRED",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  INVALID_ADDRESS: "INVALID_ADDRESS",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  CHAIN_MISMATCH: "CHAIN_MISMATCH",
  RPC_ERROR: "RPC_ERROR",
  SIGNER_MISMATCH: "SIGNER_MISMATCH",
  INTERACTIVE_COMMAND_NOT_SUPPORTED: "INTERACTIVE_COMMAND_NOT_SUPPORTED",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  APPROVAL_FAILED: "APPROVAL_FAILED",
  SWAP_FAILED: "SWAP_FAILED",
  INVALID_SPENDER: "INVALID_SPENDER",

  // Vex Agent daemon
  AGENT_START_FAILED: "AGENT_START_FAILED",
  AGENT_NOT_RUNNING: "AGENT_NOT_RUNNING",

  // Vex Agent runtime
  AGENT_VALIDATION_ERROR: "AGENT_VALIDATION_ERROR",
  AGENT_INFERENCE_FAILED: "AGENT_INFERENCE_FAILED",
  AGENT_TOOL_EXECUTION_FAILED: "AGENT_TOOL_EXECUTION_FAILED",
  AGENT_COMPACTION_FAILED: "AGENT_COMPACTION_FAILED",
  AGENT_APPROVAL_NOT_FOUND: "AGENT_APPROVAL_NOT_FOUND",
  AGENT_SCHEDULER_FAILED: "AGENT_SCHEDULER_FAILED",
  AGENT_BACKUP_FAILED: "AGENT_BACKUP_FAILED",
  AGENT_RESTORE_FAILED: "AGENT_RESTORE_FAILED",
  AGENT_EXTERNAL_SERVICE_FAILED: "AGENT_EXTERNAL_SERVICE_FAILED",

  // HTTP
  HTTP_REQUEST_FAILED: "HTTP_REQUEST_FAILED",
  HTTP_TIMEOUT: "HTTP_TIMEOUT",
  // Response body failed schema validation (codex-002). Distinct from
  // HTTP_REQUEST_FAILED so callers can treat a malformed/hostile payload as
  // non-retryable while still retrying genuine network failures.
  HTTP_RESPONSE_INVALID: "HTTP_RESPONSE_INVALID",

  // Khalani / HyperStream
  KHALANI_API_ERROR: "KHALANI_API_ERROR",
  KHALANI_TIMEOUT: "KHALANI_TIMEOUT",
  KHALANI_RATE_LIMITED: "KHALANI_RATE_LIMITED",
  KHALANI_QUOTE_NOT_FOUND: "KHALANI_QUOTE_NOT_FOUND",
  KHALANI_QUOTE_EXPIRED: "KHALANI_QUOTE_EXPIRED",
  KHALANI_VALIDATION_ERROR: "KHALANI_VALIDATION_ERROR",
  KHALANI_CANNOT_FILL: "KHALANI_CANNOT_FILL",
  KHALANI_UNSUPPORTED_TOKEN: "KHALANI_UNSUPPORTED_TOKEN",
  KHALANI_UNSUPPORTED_CHAIN: "KHALANI_UNSUPPORTED_CHAIN",
  KHALANI_DEPOSIT_FAILED: "KHALANI_DEPOSIT_FAILED",
  KHALANI_BROADCAST_FAILED: "KHALANI_BROADCAST_FAILED",
  KHALANI_PERMIT2_BLOCKED: "KHALANI_PERMIT2_BLOCKED",
  KHALANI_ORDER_NOT_FOUND: "KHALANI_ORDER_NOT_FOUND",
  KHALANI_SOLANA_SIGN_FAILED: "KHALANI_SOLANA_SIGN_FAILED",
  KHALANI_SOLANA_KEYSTORE_NOT_FOUND: "KHALANI_SOLANA_KEYSTORE_NOT_FOUND",
  KHALANI_ADDRESS_MISMATCH: "KHALANI_ADDRESS_MISMATCH",
  KHALANI_UNSUPPORTED_DEPOSIT_METHOD: "KHALANI_UNSUPPORTED_DEPOSIT_METHOD",

  // Relay (api.relay.link) — keyless cross-chain bridge
  RELAY_API_ERROR: "RELAY_API_ERROR",
  RELAY_TIMEOUT: "RELAY_TIMEOUT",
  RELAY_RATE_LIMITED: "RELAY_RATE_LIMITED",
  RELAY_UNSUPPORTED_CHAIN: "RELAY_UNSUPPORTED_CHAIN",
  RELAY_NO_ROUTE: "RELAY_NO_ROUTE",
  RELAY_UNSUPPORTED_STEP: "RELAY_UNSUPPORTED_STEP",
  RELAY_STEP_CHAIN_MISMATCH: "RELAY_STEP_CHAIN_MISMATCH",
  RELAY_BRIDGE_FAILED: "RELAY_BRIDGE_FAILED",

  // KyberSwap — shared
  KYBER_API_ERROR: "KYBER_API_ERROR",
  KYBER_TIMEOUT: "KYBER_TIMEOUT",
  KYBER_RATE_LIMITED: "KYBER_RATE_LIMITED",
  KYBER_UNSUPPORTED_CHAIN: "KYBER_UNSUPPORTED_CHAIN",

  // KyberSwap Aggregator
  KYBER_ROUTE_NOT_FOUND: "KYBER_ROUTE_NOT_FOUND",
  KYBER_TOKEN_NOT_FOUND: "KYBER_TOKEN_NOT_FOUND",
  KYBER_BUILD_FAILED: "KYBER_BUILD_FAILED",
  KYBER_MALFORMED_PARAMS: "KYBER_MALFORMED_PARAMS",
  KYBER_FEE_EXCEEDS_AMOUNT: "KYBER_FEE_EXCEEDS_AMOUNT",
  KYBER_AMOUNT_TOO_LARGE: "KYBER_AMOUNT_TOO_LARGE",
  KYBER_WETH_NOT_CONFIGURED: "KYBER_WETH_NOT_CONFIGURED",

  // KyberSwap Token API
  KYBER_TOKEN_SEARCH_FAILED: "KYBER_TOKEN_SEARCH_FAILED",
  KYBER_HONEYPOT_CHECK_FAILED: "KYBER_HONEYPOT_CHECK_FAILED",

  // KyberSwap Limit Orders
  KYBER_LO_SIGN_FAILED: "KYBER_LO_SIGN_FAILED",
  KYBER_LO_CREATE_FAILED: "KYBER_LO_CREATE_FAILED",
  KYBER_LO_CANCEL_FAILED: "KYBER_LO_CANCEL_FAILED",
  KYBER_LO_FILL_FAILED: "KYBER_LO_FILL_FAILED",
  KYBER_LO_ORDER_NOT_FOUND: "KYBER_LO_ORDER_NOT_FOUND",
  KYBER_LO_INSUFFICIENT_ALLOWANCE: "KYBER_LO_INSUFFICIENT_ALLOWANCE",
  KYBER_LO_SIGNATURE_INVALID: "KYBER_LO_SIGNATURE_INVALID",

  // KyberSwap ZaaS
  KYBER_ZAP_ROUTE_NOT_FOUND: "KYBER_ZAP_ROUTE_NOT_FOUND",
  KYBER_ZAP_BUILD_FAILED: "KYBER_ZAP_BUILD_FAILED",
  KYBER_ZAP_UNSUPPORTED_DEX: "KYBER_ZAP_UNSUPPORTED_DEX",
  KYBER_ZAP_INVALID_POSITION: "KYBER_ZAP_INVALID_POSITION",

  // Polymarket
  POLYMARKET_API_ERROR: "POLYMARKET_API_ERROR",
  POLYMARKET_TIMEOUT: "POLYMARKET_TIMEOUT",
  POLYMARKET_RATE_LIMITED: "POLYMARKET_RATE_LIMITED",
  POLYMARKET_AUTH_FAILED: "POLYMARKET_AUTH_FAILED",
  POLYMARKET_ORDER_FAILED: "POLYMARKET_ORDER_FAILED",
  POLYMARKET_ORDER_NOT_FOUND: "POLYMARKET_ORDER_NOT_FOUND",
  POLYMARKET_MARKET_NOT_FOUND: "POLYMARKET_MARKET_NOT_FOUND",
  POLYMARKET_INSUFFICIENT_BALANCE: "POLYMARKET_INSUFFICIENT_BALANCE",
  POLYMARKET_NOT_CONFIGURED: "POLYMARKET_NOT_CONFIGURED",

  // Setup
  SETUP_TARGET_EXISTS: "SETUP_TARGET_EXISTS",
  SETUP_LINK_FAILED: "SETUP_LINK_FAILED",
  SETUP_SOURCE_NOT_FOUND: "SETUP_SOURCE_NOT_FOUND",
  SYSTEM_CHECK_FAILED: "SYSTEM_CHECK_FAILED",
  CONNECTOR_WRITE_FAILED: "CONNECTOR_WRITE_FAILED",
  SETUP_CANCELLED: "SETUP_CANCELLED",

  // Openclaw
  OPENCLAW_CONFIG_WRITE_FAILED: "OPENCLAW_CONFIG_WRITE_FAILED",
  OPENCLAW_CONFIG_PARSE_FAILED: "OPENCLAW_CONFIG_PARSE_FAILED",
  OPENCLAW_HOOKS_VALIDATION_FAILED: "OPENCLAW_HOOKS_VALIDATION_FAILED",
  OPENCLAW_HOOKS_TOKEN_MISMATCH: "OPENCLAW_HOOKS_TOKEN_MISMATCH",
  OPENCLAW_HOOKS_PROBE_FAILED: "OPENCLAW_HOOKS_PROBE_FAILED",

  KEYSTORE_CORRUPT: "KEYSTORE_CORRUPT",

  // Wallet import/export
  INVALID_PRIVATE_KEY: "INVALID_PRIVATE_KEY",
  EXPORT_BLOCKED_HEADLESS: "EXPORT_BLOCKED_HEADLESS",
  EXPORT_REQUIRES_ACKNOWLEDGE: "EXPORT_REQUIRES_ACKNOWLEDGE",

  // Backup
  BACKUP_NOT_FOUND: "BACKUP_NOT_FOUND",
  BACKUP_CREATE_FAILED: "BACKUP_CREATE_FAILED",
  AUTO_BACKUP_FAILED: "AUTO_BACKUP_FAILED",

  // Backup archive restore
  ARCHIVE_MANIFEST_MALFORMED: "ARCHIVE_MANIFEST_MALFORMED",
  ARCHIVE_INCOMPLETE: "ARCHIVE_INCOMPLETE",
  ARCHIVE_RESTORE_FAILED: "ARCHIVE_RESTORE_FAILED",
  WALLET_USER_REJECTED: "WALLET_USER_REJECTED",

  // Bot
  BOT_ALREADY_RUNNING: "BOT_ALREADY_RUNNING",
  BOT_NOT_RUNNING: "BOT_NOT_RUNNING",
  BOT_ORDER_NOT_FOUND: "BOT_ORDER_NOT_FOUND",
  BOT_INVALID_TRIGGER: "BOT_INVALID_TRIGGER",
  BOT_INVALID_ORDER: "BOT_INVALID_ORDER",
  BOT_STREAM_FAILED: "BOT_STREAM_FAILED",
  BOT_TRADE_FAILED: "BOT_TRADE_FAILED",
  BOT_GUARDRAIL_EXCEEDED: "BOT_GUARDRAIL_EXCEEDED",

  // Update Daemon
  UPDATE_DAEMON_ALREADY_RUNNING: "UPDATE_DAEMON_ALREADY_RUNNING",
  UPDATE_DAEMON_NOT_RUNNING: "UPDATE_DAEMON_NOT_RUNNING",

  // Guardrails
  WALLET_MUTATION_BLOCKED_HEADLESS: "WALLET_MUTATION_BLOCKED_HEADLESS",

  // Onboard
  ONBOARD_REQUIRES_TTY: "ONBOARD_REQUIRES_TTY",

  // Claude Proxy
  CLAUDE_PROXY_ALREADY_RUNNING: "CLAUDE_PROXY_ALREADY_RUNNING",
  CLAUDE_PROXY_NOT_RUNNING: "CLAUDE_PROXY_NOT_RUNNING",
  CLAUDE_PROXY_START_FAILED: "CLAUDE_PROXY_START_FAILED",
  CLAUDE_CONFIG_PARSE_FAILED: "CLAUDE_CONFIG_PARSE_FAILED",
  CLAUDE_CONFIG_WRITE_FAILED: "CLAUDE_CONFIG_WRITE_FAILED",
  CLAUDE_CONFIG_RESTORE_FAILED: "CLAUDE_CONFIG_RESTORE_FAILED",
  CLAUDE_CONFIG_NOT_CONFIGURED: "CLAUDE_CONFIG_NOT_CONFIGURED",

  // Launcher
  LAUNCHER_START_FAILED: "LAUNCHER_START_FAILED",
  LAUNCHER_NOT_RUNNING: "LAUNCHER_NOT_RUNNING",

  // Solana
  SOLANA_INVALID_ADDRESS: "SOLANA_INVALID_ADDRESS",
  SOLANA_INSUFFICIENT_BALANCE: "SOLANA_INSUFFICIENT_BALANCE",
  SOLANA_TRANSFER_FAILED: "SOLANA_TRANSFER_FAILED",
  SOLANA_TX_FAILED: "SOLANA_TX_FAILED",
  SOLANA_TX_TIMEOUT: "SOLANA_TX_TIMEOUT",
  SOLANA_TOKEN_NOT_FOUND: "SOLANA_TOKEN_NOT_FOUND",
  SOLANA_RPC_ERROR: "SOLANA_RPC_ERROR",
  SOLANA_QUOTE_FAILED: "SOLANA_QUOTE_FAILED",
  SOLANA_SWAP_FAILED: "SOLANA_SWAP_FAILED",
  SOLANA_STAKE_FAILED: "SOLANA_STAKE_FAILED",
  SOLANA_ORDER_FAILED: "SOLANA_ORDER_FAILED",


  // Jupiter Portfolio
  SOLANA_PORTFOLIO_FAILED: "SOLANA_PORTFOLIO_FAILED",

  // Jupiter Lend
  SOLANA_LEND_DEPOSIT_FAILED: "SOLANA_LEND_DEPOSIT_FAILED",
  SOLANA_LEND_WITHDRAW_FAILED: "SOLANA_LEND_WITHDRAW_FAILED",
  SOLANA_LEND_RATES_FAILED: "SOLANA_LEND_RATES_FAILED",

  // Jupiter Send
  SOLANA_SEND_INVITE_FAILED: "SOLANA_SEND_INVITE_FAILED",
  SOLANA_SEND_CLAWBACK_FAILED: "SOLANA_SEND_CLAWBACK_FAILED",

  // Jupiter Prediction
  SOLANA_PREDICT_ORDER_FAILED: "SOLANA_PREDICT_ORDER_FAILED",
  SOLANA_PREDICT_CLAIM_FAILED: "SOLANA_PREDICT_CLAIM_FAILED",

  // Jupiter Studio
  SOLANA_STUDIO_CREATE_FAILED: "SOLANA_STUDIO_CREATE_FAILED",
  SOLANA_STUDIO_CLAIM_FAILED: "SOLANA_STUDIO_CLAIM_FAILED",

  // Solana LP
  SOLANA_LP_POOL_NOT_FOUND: "SOLANA_LP_POOL_NOT_FOUND",
  SOLANA_LP_POSITION_NOT_FOUND: "SOLANA_LP_POSITION_NOT_FOUND",
  SOLANA_LP_DEPOSIT_FAILED: "SOLANA_LP_DEPOSIT_FAILED",
  SOLANA_LP_WITHDRAW_FAILED: "SOLANA_LP_WITHDRAW_FAILED",
  SOLANA_LP_CLAIM_FAILED: "SOLANA_LP_CLAIM_FAILED",

  // DexScreener
  DEXSCREENER_API_ERROR: "DEXSCREENER_API_ERROR",
  DEXSCREENER_RATE_LIMITED: "DEXSCREENER_RATE_LIMITED",
  DEXSCREENER_TIMEOUT: "DEXSCREENER_TIMEOUT",
  DEXSCREENER_INVALID_RESPONSE: "DEXSCREENER_INVALID_RESPONSE",
  DEXSCREENER_NOT_FOUND: "DEXSCREENER_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
