import type { ProtocolToolManifest } from "../../../types.js";

export const ACCOUNT_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "chainscan.account.balance",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Get native 0G token balance for an address on 0G Network.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "0G address (0x...)." },
      { key: "tag", type: "string", description: "Block tag: latest_state, latest_mined, latest_finalized, latest_confirmed, latest_checkpoint, earliest." },
    ],
    exampleParams: { address: "0x1234567890abcdef1234567890abcdef12345678" },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.account.balanceMulti",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Get native 0G balances for up to 20 addresses in one call.",
    mutating: false,
    params: [
      { key: "addresses", type: "string", required: true, description: "Comma-separated 0G addresses (max 20)." },
      { key: "tag", type: "string", description: "Block tag (default: latest_state)." },
    ],
    exampleParams: { addresses: "0xaaa...,0xbbb..." },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.account.transactions",
    namespace: "chainscan",
    lifecycle: "active",
    description: "List transactions for an address on 0G Network with pagination and block range filtering.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "0G address (0x...)." },
      { key: "page", type: "number", description: "Page number (default: 1)." },
      { key: "offset", type: "number", description: "Results per page (default: 25, max 100)." },
      { key: "sort", type: "string", description: "Sort order: asc or desc (default: desc)." },
      { key: "startblock", type: "number", description: "Start block number." },
      { key: "endblock", type: "number", description: "End block number." },
    ],
    exampleParams: { address: "0x1234...", page: 1, offset: 25, sort: "desc" },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.account.tokenTransfers",
    namespace: "chainscan",
    lifecycle: "active",
    description: "List ERC-20 token transfers for an address. Optionally filter by token contract.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "0G address (0x...)." },
      { key: "contractaddress", type: "string", description: "Filter by specific token contract address." },
      { key: "page", type: "number", description: "Page number (default: 1)." },
      { key: "offset", type: "number", description: "Results per page (default: 25, max 100)." },
      { key: "sort", type: "string", description: "Sort order: asc or desc (default: desc)." },
      { key: "startblock", type: "number", description: "Start block number." },
      { key: "endblock", type: "number", description: "End block number." },
    ],
    exampleParams: { address: "0x1234..." },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.account.nftTransfers",
    namespace: "chainscan",
    lifecycle: "active",
    description: "List NFT (ERC-721) transfers for an address. Optionally filter by NFT contract.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "0G address (0x...)." },
      { key: "contractaddress", type: "string", description: "Filter by specific NFT contract address." },
      { key: "page", type: "number", description: "Page number (default: 1)." },
      { key: "offset", type: "number", description: "Results per page (default: 25, max 100)." },
      { key: "sort", type: "string", description: "Sort order: asc or desc (default: desc)." },
      { key: "startblock", type: "number", description: "Start block number." },
      { key: "endblock", type: "number", description: "End block number." },
    ],
    exampleParams: { address: "0x1234..." },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.account.tokenBalance",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Get balance of a specific ERC-20 token for an address on 0G Network.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "Holder address (0x...)." },
      { key: "contractAddress", type: "string", required: true, description: "ERC-20 token contract address." },
    ],
    exampleParams: { address: "0x1234...", contractAddress: "0xabcd..." },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
];
