import type { ProtocolToolManifest } from "../../../types.js";

export const STATS_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "chainscan.stats.holders",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Token holder count over time on 0G Network — detect accumulation or distribution patterns.",
    mutating: false,
    params: [
      { key: "contract", type: "string", required: true, description: "Token contract address." },
      { key: "skip", type: "number", description: "Records to skip (default: 0, max 10000)." },
      { key: "limit", type: "number", description: "Max results (default: 30, max 2000)." },
      { key: "sort", type: "string", description: "Sort order: asc or desc (default: desc)." },
      { key: "minTimestamp", type: "number", description: "Start timestamp filter (Unix seconds)." },
      { key: "maxTimestamp", type: "number", description: "End timestamp filter (Unix seconds)." },
    ],
    exampleParams: { contract: "0xabcd...", limit: 30, sort: "desc" },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.stats.transfers",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Token transfer count and unique user count over time — measure token activity and adoption.",
    mutating: false,
    params: [
      { key: "contract", type: "string", required: true, description: "Token contract address." },
      { key: "skip", type: "number", description: "Records to skip (default: 0, max 10000)." },
      { key: "limit", type: "number", description: "Max results (default: 30, max 2000)." },
      { key: "sort", type: "string", description: "Sort order: asc or desc (default: desc)." },
      { key: "minTimestamp", type: "number", description: "Start timestamp filter (Unix seconds)." },
      { key: "maxTimestamp", type: "number", description: "End timestamp filter (Unix seconds)." },
    ],
    exampleParams: { contract: "0xabcd...", limit: 30 },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.stats.participants",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Unique participant count over time for a token — track growing or shrinking user base.",
    mutating: false,
    params: [
      { key: "contract", type: "string", required: true, description: "Token contract address." },
      { key: "skip", type: "number", description: "Records to skip (default: 0, max 10000)." },
      { key: "limit", type: "number", description: "Max results (default: 30, max 2000)." },
      { key: "sort", type: "string", description: "Sort order: asc or desc (default: desc)." },
      { key: "minTimestamp", type: "number", description: "Start timestamp filter (Unix seconds)." },
      { key: "maxTimestamp", type: "number", description: "End timestamp filter (Unix seconds)." },
    ],
    exampleParams: { contract: "0xabcd...", limit: 30 },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.stats.topSenders",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Top token senders by volume on 0G Network over a time span (24h, 3d, or 7d).",
    mutating: false,
    params: [
      { key: "spanType", type: "string", description: "Time span: 24h, 3d, or 7d (default: 24h)." },
    ],
    exampleParams: { spanType: "24h" },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.stats.topReceivers",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Top token receivers by volume on 0G Network over a time span (24h, 3d, or 7d).",
    mutating: false,
    params: [
      { key: "spanType", type: "string", description: "Time span: 24h, 3d, or 7d (default: 24h)." },
    ],
    exampleParams: { spanType: "24h" },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
  {
    toolId: "chainscan.stats.topParticipants",
    namespace: "chainscan",
    lifecycle: "active",
    description: "Top token participants (senders + receivers) by volume on 0G Network over a time span (24h, 3d, or 7d).",
    mutating: false,
    params: [
      { key: "spanType", type: "string", description: "Time span: 24h, 3d, or 7d (default: 24h)." },
    ],
    exampleParams: { spanType: "24h" },
    requiresEnv: "CHAINSCAN_API_KEY",
  },
];
